// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

/**
 *
 *
 * <pre>
 * Certificate attribute dictionary.
 * </pre>
 *
 * Protobuf type {@code com.webank.wedpr.scd.proto.AttributeDict}
 */
public final class AttributeDict extends com.google.protobuf.GeneratedMessageV3
        implements
        // @@protoc_insertion_point(message_implements:com.webank.wedpr.scd.proto.AttributeDict)
        AttributeDictOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use AttributeDict.newBuilder() to construct.
    private AttributeDict(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AttributeDict() {
        pair_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(UnusedPrivateParameter unused) {
        return new AttributeDict();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
    }

    private AttributeDict(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10:
                        {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                pair_ =
                                        new java.util.ArrayList<
                                                com.webank.wedpr.scd.proto.StringToStringPair>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            pair_.add(
                                    input.readMessage(
                                            com.webank.wedpr.scd.proto.StringToStringPair.parser(),
                                            extensionRegistry));
                            break;
                        }
                    default:
                        {
                            if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                    .setUnfinishedMessage(this);
        } finally {
            if (((mutable_bitField0_ & 0x00000001) != 0)) {
                pair_ = java.util.Collections.unmodifiableList(pair_);
            }
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.webank.wedpr.scd.proto.Scd
                .internal_static_com_webank_wedpr_scd_proto_AttributeDict_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
        return com.webank.wedpr.scd.proto.Scd
                .internal_static_com_webank_wedpr_scd_proto_AttributeDict_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.webank.wedpr.scd.proto.AttributeDict.class,
                        com.webank.wedpr.scd.proto.AttributeDict.Builder.class);
    }

    public static final int PAIR_FIELD_NUMBER = 1;
    private java.util.List<com.webank.wedpr.scd.proto.StringToStringPair> pair_;
    /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
    public java.util.List<com.webank.wedpr.scd.proto.StringToStringPair> getPairList() {
        return pair_;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
    public java.util.List<? extends com.webank.wedpr.scd.proto.StringToStringPairOrBuilder>
            getPairOrBuilderList() {
        return pair_;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
    public int getPairCount() {
        return pair_.size();
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
    public com.webank.wedpr.scd.proto.StringToStringPair getPair(int index) {
        return pair_.get(index);
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
    public com.webank.wedpr.scd.proto.StringToStringPairOrBuilder getPairOrBuilder(int index) {
        return pair_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        for (int i = 0; i < pair_.size(); i++) {
            output.writeMessage(1, pair_.get(i));
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (int i = 0; i < pair_.size(); i++) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, pair_.get(i));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.webank.wedpr.scd.proto.AttributeDict)) {
            return super.equals(obj);
        }
        com.webank.wedpr.scd.proto.AttributeDict other =
                (com.webank.wedpr.scd.proto.AttributeDict) obj;

        if (!getPairList().equals(other.getPairList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getPairCount() > 0) {
            hash = (37 * hash) + PAIR_FIELD_NUMBER;
            hash = (53 * hash) + getPairList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(
            byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
                PARSER, input, extensionRegistry);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseDelimitedFrom(
            java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
                PARSER, input, extensionRegistry);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(
            com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.webank.wedpr.scd.proto.AttributeDict parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
                PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.webank.wedpr.scd.proto.AttributeDict prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }
    /**
     *
     *
     * <pre>
     * Certificate attribute dictionary.
     * </pre>
     *
     * Protobuf type {@code com.webank.wedpr.scd.proto.AttributeDict}
     */
    public static final class Builder
            extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
            implements
            // @@protoc_insertion_point(builder_implements:com.webank.wedpr.scd.proto.AttributeDict)
            com.webank.wedpr.scd.proto.AttributeDictOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.webank.wedpr.scd.proto.Scd
                    .internal_static_com_webank_wedpr_scd_proto_AttributeDict_descriptor;
        }

        @Override
        protected FieldAccessorTable internalGetFieldAccessorTable() {
            return com.webank.wedpr.scd.proto.Scd
                    .internal_static_com_webank_wedpr_scd_proto_AttributeDict_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.webank.wedpr.scd.proto.AttributeDict.class,
                            com.webank.wedpr.scd.proto.AttributeDict.Builder.class);
        }

        // Construct using com.webank.wedpr.scd.proto.AttributeDict.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
                getPairFieldBuilder();
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            if (pairBuilder_ == null) {
                pair_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
            } else {
                pairBuilder_.clear();
            }
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.webank.wedpr.scd.proto.Scd
                    .internal_static_com_webank_wedpr_scd_proto_AttributeDict_descriptor;
        }

        @Override
        public com.webank.wedpr.scd.proto.AttributeDict getDefaultInstanceForType() {
            return com.webank.wedpr.scd.proto.AttributeDict.getDefaultInstance();
        }

        @Override
        public com.webank.wedpr.scd.proto.AttributeDict build() {
            com.webank.wedpr.scd.proto.AttributeDict result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public com.webank.wedpr.scd.proto.AttributeDict buildPartial() {
            com.webank.wedpr.scd.proto.AttributeDict result =
                    new com.webank.wedpr.scd.proto.AttributeDict(this);
            int from_bitField0_ = bitField0_;
            if (pairBuilder_ == null) {
                if (((bitField0_ & 0x00000001) != 0)) {
                    pair_ = java.util.Collections.unmodifiableList(pair_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.pair_ = pair_;
            } else {
                result.pair_ = pairBuilder_.build();
            }
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.webank.wedpr.scd.proto.AttributeDict) {
                return mergeFrom((com.webank.wedpr.scd.proto.AttributeDict) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.webank.wedpr.scd.proto.AttributeDict other) {
            if (other == com.webank.wedpr.scd.proto.AttributeDict.getDefaultInstance()) return this;
            if (pairBuilder_ == null) {
                if (!other.pair_.isEmpty()) {
                    if (pair_.isEmpty()) {
                        pair_ = other.pair_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensurePairIsMutable();
                        pair_.addAll(other.pair_);
                    }
                    onChanged();
                }
            } else {
                if (!other.pair_.isEmpty()) {
                    if (pairBuilder_.isEmpty()) {
                        pairBuilder_.dispose();
                        pairBuilder_ = null;
                        pair_ = other.pair_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                        pairBuilder_ =
                                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                                        ? getPairFieldBuilder()
                                        : null;
                    } else {
                        pairBuilder_.addAllMessages(other.pair_);
                    }
                }
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.webank.wedpr.scd.proto.AttributeDict parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.webank.wedpr.scd.proto.AttributeDict) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private java.util.List<com.webank.wedpr.scd.proto.StringToStringPair> pair_ =
                java.util.Collections.emptyList();

        private void ensurePairIsMutable() {
            if (!((bitField0_ & 0x00000001) != 0)) {
                pair_ =
                        new java.util.ArrayList<com.webank.wedpr.scd.proto.StringToStringPair>(
                                pair_);
                bitField0_ |= 0x00000001;
            }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                        com.webank.wedpr.scd.proto.StringToStringPair,
                        com.webank.wedpr.scd.proto.StringToStringPair.Builder,
                        com.webank.wedpr.scd.proto.StringToStringPairOrBuilder>
                pairBuilder_;

        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public java.util.List<com.webank.wedpr.scd.proto.StringToStringPair> getPairList() {
            if (pairBuilder_ == null) {
                return java.util.Collections.unmodifiableList(pair_);
            } else {
                return pairBuilder_.getMessageList();
            }
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public int getPairCount() {
            if (pairBuilder_ == null) {
                return pair_.size();
            } else {
                return pairBuilder_.getCount();
            }
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public com.webank.wedpr.scd.proto.StringToStringPair getPair(int index) {
            if (pairBuilder_ == null) {
                return pair_.get(index);
            } else {
                return pairBuilder_.getMessage(index);
            }
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder setPair(int index, com.webank.wedpr.scd.proto.StringToStringPair value) {
            if (pairBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePairIsMutable();
                pair_.set(index, value);
                onChanged();
            } else {
                pairBuilder_.setMessage(index, value);
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder setPair(
                int index, com.webank.wedpr.scd.proto.StringToStringPair.Builder builderForValue) {
            if (pairBuilder_ == null) {
                ensurePairIsMutable();
                pair_.set(index, builderForValue.build());
                onChanged();
            } else {
                pairBuilder_.setMessage(index, builderForValue.build());
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder addPair(com.webank.wedpr.scd.proto.StringToStringPair value) {
            if (pairBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePairIsMutable();
                pair_.add(value);
                onChanged();
            } else {
                pairBuilder_.addMessage(value);
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder addPair(int index, com.webank.wedpr.scd.proto.StringToStringPair value) {
            if (pairBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensurePairIsMutable();
                pair_.add(index, value);
                onChanged();
            } else {
                pairBuilder_.addMessage(index, value);
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder addPair(
                com.webank.wedpr.scd.proto.StringToStringPair.Builder builderForValue) {
            if (pairBuilder_ == null) {
                ensurePairIsMutable();
                pair_.add(builderForValue.build());
                onChanged();
            } else {
                pairBuilder_.addMessage(builderForValue.build());
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder addPair(
                int index, com.webank.wedpr.scd.proto.StringToStringPair.Builder builderForValue) {
            if (pairBuilder_ == null) {
                ensurePairIsMutable();
                pair_.add(index, builderForValue.build());
                onChanged();
            } else {
                pairBuilder_.addMessage(index, builderForValue.build());
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder addAllPair(
                Iterable<? extends com.webank.wedpr.scd.proto.StringToStringPair> values) {
            if (pairBuilder_ == null) {
                ensurePairIsMutable();
                com.google.protobuf.AbstractMessageLite.Builder.addAll(values, pair_);
                onChanged();
            } else {
                pairBuilder_.addAllMessages(values);
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder clearPair() {
            if (pairBuilder_ == null) {
                pair_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
            } else {
                pairBuilder_.clear();
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public Builder removePair(int index) {
            if (pairBuilder_ == null) {
                ensurePairIsMutable();
                pair_.remove(index);
                onChanged();
            } else {
                pairBuilder_.remove(index);
            }
            return this;
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public com.webank.wedpr.scd.proto.StringToStringPair.Builder getPairBuilder(int index) {
            return getPairFieldBuilder().getBuilder(index);
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public com.webank.wedpr.scd.proto.StringToStringPairOrBuilder getPairOrBuilder(int index) {
            if (pairBuilder_ == null) {
                return pair_.get(index);
            } else {
                return pairBuilder_.getMessageOrBuilder(index);
            }
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public java.util.List<? extends com.webank.wedpr.scd.proto.StringToStringPairOrBuilder>
                getPairOrBuilderList() {
            if (pairBuilder_ != null) {
                return pairBuilder_.getMessageOrBuilderList();
            } else {
                return java.util.Collections.unmodifiableList(pair_);
            }
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public com.webank.wedpr.scd.proto.StringToStringPair.Builder addPairBuilder() {
            return getPairFieldBuilder()
                    .addBuilder(com.webank.wedpr.scd.proto.StringToStringPair.getDefaultInstance());
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public com.webank.wedpr.scd.proto.StringToStringPair.Builder addPairBuilder(int index) {
            return getPairFieldBuilder()
                    .addBuilder(
                            index,
                            com.webank.wedpr.scd.proto.StringToStringPair.getDefaultInstance());
        }
        /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
        public java.util.List<com.webank.wedpr.scd.proto.StringToStringPair.Builder>
                getPairBuilderList() {
            return getPairFieldBuilder().getBuilderList();
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
                        com.webank.wedpr.scd.proto.StringToStringPair,
                        com.webank.wedpr.scd.proto.StringToStringPair.Builder,
                        com.webank.wedpr.scd.proto.StringToStringPairOrBuilder>
                getPairFieldBuilder() {
            if (pairBuilder_ == null) {
                pairBuilder_ =
                        new com.google.protobuf.RepeatedFieldBuilderV3<
                                com.webank.wedpr.scd.proto.StringToStringPair,
                                com.webank.wedpr.scd.proto.StringToStringPair.Builder,
                                com.webank.wedpr.scd.proto.StringToStringPairOrBuilder>(
                                pair_,
                                ((bitField0_ & 0x00000001) != 0),
                                getParentForChildren(),
                                isClean());
                pair_ = null;
            }
            return pairBuilder_;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:com.webank.wedpr.scd.proto.AttributeDict)
    }

    // @@protoc_insertion_point(class_scope:com.webank.wedpr.scd.proto.AttributeDict)
    private static final com.webank.wedpr.scd.proto.AttributeDict DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new com.webank.wedpr.scd.proto.AttributeDict();
    }

    public static com.webank.wedpr.scd.proto.AttributeDict getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AttributeDict> PARSER =
            new com.google.protobuf.AbstractParser<AttributeDict>() {
                @Override
                public AttributeDict parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                    return new AttributeDict(input, extensionRegistry);
                }
            };

    public static com.google.protobuf.Parser<AttributeDict> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AttributeDict> getParserForType() {
        return PARSER;
    }

    @Override
    public com.webank.wedpr.scd.proto.AttributeDict getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }
}
