// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

public interface AttributeDictOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.scd.proto.AttributeDict)
    com.google.protobuf.MessageOrBuilder {

  /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
  java.util.List<com.webank.wedpr.scd.proto.StringToStringPair> getPairList();
  /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
  com.webank.wedpr.scd.proto.StringToStringPair getPair(int index);
  /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
  int getPairCount();
  /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
  java.util.List<? extends com.webank.wedpr.scd.proto.StringToStringPairOrBuilder>
      getPairOrBuilderList();
  /** <code>repeated .com.webank.wedpr.scd.proto.StringToStringPair pair = 1;</code> */
  com.webank.wedpr.scd.proto.StringToStringPairOrBuilder getPairOrBuilder(int index);
}
