// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

/**
 *
 *
 * <pre>
 * Certificate secret blind factors.
 * </pre>
 *
 * Protobuf type {@code com.webank.wedpr.scd.proto.BlindedCertificateSecret}
 */
public final class BlindedCertificateSecret extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.scd.proto.BlindedCertificateSecret)
    BlindedCertificateSecretOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use BlindedCertificateSecret.newBuilder() to construct.
  private BlindedCertificateSecret(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private BlindedCertificateSecret() {
    blindedCertificateSecrets_ = "";
    blindedCertificateSecretsCorrectnessProof_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new BlindedCertificateSecret();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private BlindedCertificateSecret(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              String s = input.readStringRequireUtf8();

              blindedCertificateSecrets_ = s;
              break;
            }
          case 18:
            {
              String s = input.readStringRequireUtf8();

              blindedCertificateSecretsCorrectnessProof_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.webank.wedpr.scd.proto.Scd
        .internal_static_com_webank_wedpr_scd_proto_BlindedCertificateSecret_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return com.webank.wedpr.scd.proto.Scd
        .internal_static_com_webank_wedpr_scd_proto_BlindedCertificateSecret_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.webank.wedpr.scd.proto.BlindedCertificateSecret.class,
            com.webank.wedpr.scd.proto.BlindedCertificateSecret.Builder.class);
  }

  public static final int BLINDED_CERTIFICATE_SECRETS_FIELD_NUMBER = 1;
  private volatile Object blindedCertificateSecrets_;
  /** <code>string blinded_certificate_secrets = 1;</code> */
  public String getBlindedCertificateSecrets() {
    Object ref = blindedCertificateSecrets_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blindedCertificateSecrets_ = s;
      return s;
    }
  }
  /** <code>string blinded_certificate_secrets = 1;</code> */
  public com.google.protobuf.ByteString getBlindedCertificateSecretsBytes() {
    Object ref = blindedCertificateSecrets_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      blindedCertificateSecrets_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLINDED_CERTIFICATE_SECRETS_CORRECTNESS_PROOF_FIELD_NUMBER = 2;
  private volatile Object blindedCertificateSecretsCorrectnessProof_;
  /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
  public String getBlindedCertificateSecretsCorrectnessProof() {
    Object ref = blindedCertificateSecretsCorrectnessProof_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blindedCertificateSecretsCorrectnessProof_ = s;
      return s;
    }
  }
  /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
  public com.google.protobuf.ByteString getBlindedCertificateSecretsCorrectnessProofBytes() {
    Object ref = blindedCertificateSecretsCorrectnessProof_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      blindedCertificateSecretsCorrectnessProof_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getBlindedCertificateSecretsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, blindedCertificateSecrets_);
    }
    if (!getBlindedCertificateSecretsCorrectnessProofBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(
          output, 2, blindedCertificateSecretsCorrectnessProof_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBlindedCertificateSecretsBytes().isEmpty()) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(1, blindedCertificateSecrets_);
    }
    if (!getBlindedCertificateSecretsCorrectnessProofBytes().isEmpty()) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(
              2, blindedCertificateSecretsCorrectnessProof_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.webank.wedpr.scd.proto.BlindedCertificateSecret)) {
      return super.equals(obj);
    }
    com.webank.wedpr.scd.proto.BlindedCertificateSecret other =
        (com.webank.wedpr.scd.proto.BlindedCertificateSecret) obj;

    if (!getBlindedCertificateSecrets().equals(other.getBlindedCertificateSecrets())) return false;
    if (!getBlindedCertificateSecretsCorrectnessProof()
        .equals(other.getBlindedCertificateSecretsCorrectnessProof())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLINDED_CERTIFICATE_SECRETS_FIELD_NUMBER;
    hash = (53 * hash) + getBlindedCertificateSecrets().hashCode();
    hash = (37 * hash) + BLINDED_CERTIFICATE_SECRETS_CORRECTNESS_PROOF_FIELD_NUMBER;
    hash = (53 * hash) + getBlindedCertificateSecretsCorrectnessProof().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.webank.wedpr.scd.proto.BlindedCertificateSecret prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Certificate secret blind factors.
   * </pre>
   *
   * Protobuf type {@code com.webank.wedpr.scd.proto.BlindedCertificateSecret}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.scd.proto.BlindedCertificateSecret)
      com.webank.wedpr.scd.proto.BlindedCertificateSecretOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.webank.wedpr.scd.proto.Scd
          .internal_static_com_webank_wedpr_scd_proto_BlindedCertificateSecret_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return com.webank.wedpr.scd.proto.Scd
          .internal_static_com_webank_wedpr_scd_proto_BlindedCertificateSecret_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.webank.wedpr.scd.proto.BlindedCertificateSecret.class,
              com.webank.wedpr.scd.proto.BlindedCertificateSecret.Builder.class);
    }

    // Construct using com.webank.wedpr.scd.proto.BlindedCertificateSecret.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      blindedCertificateSecrets_ = "";

      blindedCertificateSecretsCorrectnessProof_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.webank.wedpr.scd.proto.Scd
          .internal_static_com_webank_wedpr_scd_proto_BlindedCertificateSecret_descriptor;
    }

    @Override
    public com.webank.wedpr.scd.proto.BlindedCertificateSecret getDefaultInstanceForType() {
      return com.webank.wedpr.scd.proto.BlindedCertificateSecret.getDefaultInstance();
    }

    @Override
    public com.webank.wedpr.scd.proto.BlindedCertificateSecret build() {
      com.webank.wedpr.scd.proto.BlindedCertificateSecret result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.webank.wedpr.scd.proto.BlindedCertificateSecret buildPartial() {
      com.webank.wedpr.scd.proto.BlindedCertificateSecret result =
          new com.webank.wedpr.scd.proto.BlindedCertificateSecret(this);
      result.blindedCertificateSecrets_ = blindedCertificateSecrets_;
      result.blindedCertificateSecretsCorrectnessProof_ =
          blindedCertificateSecretsCorrectnessProof_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.webank.wedpr.scd.proto.BlindedCertificateSecret) {
        return mergeFrom((com.webank.wedpr.scd.proto.BlindedCertificateSecret) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.webank.wedpr.scd.proto.BlindedCertificateSecret other) {
      if (other == com.webank.wedpr.scd.proto.BlindedCertificateSecret.getDefaultInstance())
        return this;
      if (!other.getBlindedCertificateSecrets().isEmpty()) {
        blindedCertificateSecrets_ = other.blindedCertificateSecrets_;
        onChanged();
      }
      if (!other.getBlindedCertificateSecretsCorrectnessProof().isEmpty()) {
        blindedCertificateSecretsCorrectnessProof_ =
            other.blindedCertificateSecretsCorrectnessProof_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.webank.wedpr.scd.proto.BlindedCertificateSecret parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage =
            (com.webank.wedpr.scd.proto.BlindedCertificateSecret) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object blindedCertificateSecrets_ = "";
    /** <code>string blinded_certificate_secrets = 1;</code> */
    public String getBlindedCertificateSecrets() {
      Object ref = blindedCertificateSecrets_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blindedCertificateSecrets_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string blinded_certificate_secrets = 1;</code> */
    public com.google.protobuf.ByteString getBlindedCertificateSecretsBytes() {
      Object ref = blindedCertificateSecrets_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        blindedCertificateSecrets_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string blinded_certificate_secrets = 1;</code> */
    public Builder setBlindedCertificateSecrets(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      blindedCertificateSecrets_ = value;
      onChanged();
      return this;
    }
    /** <code>string blinded_certificate_secrets = 1;</code> */
    public Builder clearBlindedCertificateSecrets() {

      blindedCertificateSecrets_ = getDefaultInstance().getBlindedCertificateSecrets();
      onChanged();
      return this;
    }
    /** <code>string blinded_certificate_secrets = 1;</code> */
    public Builder setBlindedCertificateSecretsBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      blindedCertificateSecrets_ = value;
      onChanged();
      return this;
    }

    private Object blindedCertificateSecretsCorrectnessProof_ = "";
    /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
    public String getBlindedCertificateSecretsCorrectnessProof() {
      Object ref = blindedCertificateSecretsCorrectnessProof_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blindedCertificateSecretsCorrectnessProof_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
    public com.google.protobuf.ByteString getBlindedCertificateSecretsCorrectnessProofBytes() {
      Object ref = blindedCertificateSecretsCorrectnessProof_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        blindedCertificateSecretsCorrectnessProof_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
    public Builder setBlindedCertificateSecretsCorrectnessProof(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      blindedCertificateSecretsCorrectnessProof_ = value;
      onChanged();
      return this;
    }
    /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
    public Builder clearBlindedCertificateSecretsCorrectnessProof() {

      blindedCertificateSecretsCorrectnessProof_ =
          getDefaultInstance().getBlindedCertificateSecretsCorrectnessProof();
      onChanged();
      return this;
    }
    /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
    public Builder setBlindedCertificateSecretsCorrectnessProofBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      blindedCertificateSecretsCorrectnessProof_ = value;
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.scd.proto.BlindedCertificateSecret)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.scd.proto.BlindedCertificateSecret)
  private static final com.webank.wedpr.scd.proto.BlindedCertificateSecret DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.webank.wedpr.scd.proto.BlindedCertificateSecret();
  }

  public static com.webank.wedpr.scd.proto.BlindedCertificateSecret getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlindedCertificateSecret> PARSER =
      new com.google.protobuf.AbstractParser<BlindedCertificateSecret>() {
        @Override
        public BlindedCertificateSecret parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlindedCertificateSecret(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<BlindedCertificateSecret> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BlindedCertificateSecret> getParserForType() {
    return PARSER;
  }

  @Override
  public com.webank.wedpr.scd.proto.BlindedCertificateSecret getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
