// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

public interface CertificateSchemaOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.scd.proto.CertificateSchema)
    com.google.protobuf.MessageOrBuilder {

  /** <code>repeated string attribute_name = 1;</code> */
  java.util.List<String> getAttributeNameList();
  /** <code>repeated string attribute_name = 1;</code> */
  int getAttributeNameCount();
  /** <code>repeated string attribute_name = 1;</code> */
  String getAttributeName(int index);
  /** <code>repeated string attribute_name = 1;</code> */
  com.google.protobuf.ByteString getAttributeNameBytes(int index);
}
