// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

public interface ScdResultOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:com.webank.wedpr.scd.proto.ScdResult)
        com.google.protobuf.MessageOrBuilder {

    /**
     *
     *
     * <pre>
     * Used by the issuer.
     * </pre>
     *
     * <code>.com.webank.wedpr.scd.proto.CertificateTemplate certificate_template = 1;</code>
     */
    boolean hasCertificateTemplate();
    /**
     *
     *
     * <pre>
     * Used by the issuer.
     * </pre>
     *
     * <code>.com.webank.wedpr.scd.proto.CertificateTemplate certificate_template = 1;</code>
     */
    com.webank.wedpr.scd.proto.CertificateTemplate getCertificateTemplate();
    /**
     *
     *
     * <pre>
     * Used by the issuer.
     * </pre>
     *
     * <code>.com.webank.wedpr.scd.proto.CertificateTemplate certificate_template = 1;</code>
     */
    com.webank.wedpr.scd.proto.CertificateTemplateOrBuilder getCertificateTemplateOrBuilder();

    /** <code>.com.webank.wedpr.scd.proto.TemplatePrivateKey template_private_key = 2;</code> */
    boolean hasTemplatePrivateKey();
    /** <code>.com.webank.wedpr.scd.proto.TemplatePrivateKey template_private_key = 2;</code> */
    com.webank.wedpr.scd.proto.TemplatePrivateKey getTemplatePrivateKey();
    /** <code>.com.webank.wedpr.scd.proto.TemplatePrivateKey template_private_key = 2;</code> */
    com.webank.wedpr.scd.proto.TemplatePrivateKeyOrBuilder getTemplatePrivateKeyOrBuilder();

    /** <code>string issuer_nonce = 3;</code> */
    String getIssuerNonce();
    /** <code>string issuer_nonce = 3;</code> */
    com.google.protobuf.ByteString getIssuerNonceBytes();

    /**
     *
     *
     * <pre>
     * Used by the user.
     * </pre>
     *
     * <code>.com.webank.wedpr.scd.proto.CertificateSignature certificate_signature = 4;</code>
     */
    boolean hasCertificateSignature();
    /**
     *
     *
     * <pre>
     * Used by the user.
     * </pre>
     *
     * <code>.com.webank.wedpr.scd.proto.CertificateSignature certificate_signature = 4;</code>
     */
    com.webank.wedpr.scd.proto.CertificateSignature getCertificateSignature();
    /**
     *
     *
     * <pre>
     * Used by the user.
     * </pre>
     *
     * <code>.com.webank.wedpr.scd.proto.CertificateSignature certificate_signature = 4;</code>
     */
    com.webank.wedpr.scd.proto.CertificateSignatureOrBuilder getCertificateSignatureOrBuilder();

    /** <code>string user_nonce = 5;</code> */
    String getUserNonce();
    /** <code>string user_nonce = 5;</code> */
    com.google.protobuf.ByteString getUserNonceBytes();

    /**
     * <code>.com.webank.wedpr.scd.proto.SignCertificateRequest sign_certificate_request = 6;</code>
     */
    boolean hasSignCertificateRequest();
    /**
     * <code>.com.webank.wedpr.scd.proto.SignCertificateRequest sign_certificate_request = 6;</code>
     */
    com.webank.wedpr.scd.proto.SignCertificateRequest getSignCertificateRequest();
    /**
     * <code>.com.webank.wedpr.scd.proto.SignCertificateRequest sign_certificate_request = 6;</code>
     */
    com.webank.wedpr.scd.proto.SignCertificateRequestOrBuilder getSignCertificateRequestOrBuilder();

    /** <code>string user_private_key = 7;</code> */
    String getUserPrivateKey();
    /** <code>string user_private_key = 7;</code> */
    com.google.protobuf.ByteString getUserPrivateKeyBytes();

    /** <code>string certificate_secrets_blinding_factors = 8;</code> */
    String getCertificateSecretsBlindingFactors();
    /** <code>string certificate_secrets_blinding_factors = 8;</code> */
    com.google.protobuf.ByteString getCertificateSecretsBlindingFactorsBytes();

    /**
     *
     *
     * <pre>
     * Used by the verifier.
     * </pre>
     *
     * <code>string verification_nonce = 9;</code>
     */
    String getVerificationNonce();
    /**
     *
     *
     * <pre>
     * Used by the verifier.
     * </pre>
     *
     * <code>string verification_nonce = 9;</code>
     */
    com.google.protobuf.ByteString getVerificationNonceBytes();

    /** <code>.com.webank.wedpr.scd.proto.VerifyRequest verify_request = 10;</code> */
    boolean hasVerifyRequest();
    /** <code>.com.webank.wedpr.scd.proto.VerifyRequest verify_request = 10;</code> */
    com.webank.wedpr.scd.proto.VerifyRequest getVerifyRequest();
    /** <code>.com.webank.wedpr.scd.proto.VerifyRequest verify_request = 10;</code> */
    com.webank.wedpr.scd.proto.VerifyRequestOrBuilder getVerifyRequestOrBuilder();

    /** <code>.com.webank.wedpr.scd.proto.AttributeDict revealed_attribute_dict = 11;</code> */
    boolean hasRevealedAttributeDict();
    /** <code>.com.webank.wedpr.scd.proto.AttributeDict revealed_attribute_dict = 11;</code> */
    com.webank.wedpr.scd.proto.AttributeDict getRevealedAttributeDict();
    /** <code>.com.webank.wedpr.scd.proto.AttributeDict revealed_attribute_dict = 11;</code> */
    com.webank.wedpr.scd.proto.AttributeDictOrBuilder getRevealedAttributeDictOrBuilder();

    /** <code>bool bool_result = 12;</code> */
    boolean getBoolResult();
}
