// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

public interface TemplatePublicKeyOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:com.webank.wedpr.scd.proto.TemplatePublicKey)
        com.google.protobuf.MessageOrBuilder {

    /** <code>string key = 1;</code> */
    String getKey();
    /** <code>string key = 1;</code> */
    com.google.protobuf.ByteString getKeyBytes();
}
