// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

public interface VerificationRuleSetOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:com.webank.wedpr.scd.proto.VerificationRuleSet)
        com.google.protobuf.MessageOrBuilder {

    /** <code>repeated string revealed_attribute_name = 1;</code> */
    java.util.List<String> getRevealedAttributeNameList();
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    int getRevealedAttributeNameCount();
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    String getRevealedAttributeName(int index);
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    com.google.protobuf.ByteString getRevealedAttributeNameBytes(int index);

    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    java.util.List<com.webank.wedpr.scd.proto.Predicate> getAttributePredicateList();
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    com.webank.wedpr.scd.proto.Predicate getAttributePredicate(int index);
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    int getAttributePredicateCount();
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    java.util.List<? extends com.webank.wedpr.scd.proto.PredicateOrBuilder>
            getAttributePredicateOrBuilderList();
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    com.webank.wedpr.scd.proto.PredicateOrBuilder getAttributePredicateOrBuilder(int index);
}
