// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

/** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.AttributeTemplate} */
public final class AttributeTemplate extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.selective_disclosure.proto.AttributeTemplate)
    AttributeTemplateOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use AttributeTemplate.newBuilder() to construct.
  private AttributeTemplate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private AttributeTemplate() {
    attributeKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new AttributeTemplate();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private AttributeTemplate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                attributeKey_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              attributeKey_.add(s);
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        attributeKey_ = attributeKey_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_AttributeTemplate_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_AttributeTemplate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(AttributeTemplate.class, Builder.class);
  }

  public static final int ATTRIBUTE_KEY_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList attributeKey_;
  /** <code>repeated string attribute_key = 1;</code> */
  public com.google.protobuf.ProtocolStringList getAttributeKeyList() {
    return attributeKey_;
  }
  /** <code>repeated string attribute_key = 1;</code> */
  public int getAttributeKeyCount() {
    return attributeKey_.size();
  }
  /** <code>repeated string attribute_key = 1;</code> */
  public String getAttributeKey(int index) {
    return attributeKey_.get(index);
  }
  /** <code>repeated string attribute_key = 1;</code> */
  public com.google.protobuf.ByteString getAttributeKeyBytes(int index) {
    return attributeKey_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    for (int i = 0; i < attributeKey_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, attributeKey_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < attributeKey_.size(); i++) {
        dataSize += computeStringSizeNoTag(attributeKey_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAttributeKeyList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof AttributeTemplate)) {
      return super.equals(obj);
    }
    AttributeTemplate other = (AttributeTemplate) obj;

    if (!getAttributeKeyList().equals(other.getAttributeKeyList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAttributeKeyCount() > 0) {
      hash = (37 * hash) + ATTRIBUTE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getAttributeKeyList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AttributeTemplate parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static AttributeTemplate parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static AttributeTemplate parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static AttributeTemplate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static AttributeTemplate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static AttributeTemplate parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static AttributeTemplate parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static AttributeTemplate parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static AttributeTemplate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static AttributeTemplate parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static AttributeTemplate parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static AttributeTemplate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(AttributeTemplate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.AttributeTemplate} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.selective_disclosure.proto.AttributeTemplate)
      AttributeTemplateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_AttributeTemplate_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_AttributeTemplate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(AttributeTemplate.class, Builder.class);
    }

    // Construct using com.webank.wedpr.selectivedisclosure.proto.AttributeTemplate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      attributeKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_AttributeTemplate_descriptor;
    }

    @Override
    public AttributeTemplate getDefaultInstanceForType() {
      return AttributeTemplate.getDefaultInstance();
    }

    @Override
    public AttributeTemplate build() {
      AttributeTemplate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public AttributeTemplate buildPartial() {
      AttributeTemplate result = new AttributeTemplate(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        attributeKey_ = attributeKey_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.attributeKey_ = attributeKey_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AttributeTemplate) {
        return mergeFrom((AttributeTemplate) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AttributeTemplate other) {
      if (other == AttributeTemplate.getDefaultInstance()) return this;
      if (!other.attributeKey_.isEmpty()) {
        if (attributeKey_.isEmpty()) {
          attributeKey_ = other.attributeKey_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAttributeKeyIsMutable();
          attributeKey_.addAll(other.attributeKey_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AttributeTemplate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AttributeTemplate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.LazyStringList attributeKey_ =
        com.google.protobuf.LazyStringArrayList.EMPTY;

    private void ensureAttributeKeyIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        attributeKey_ = new com.google.protobuf.LazyStringArrayList(attributeKey_);
        bitField0_ |= 0x00000001;
      }
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public com.google.protobuf.ProtocolStringList getAttributeKeyList() {
      return attributeKey_.getUnmodifiableView();
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public int getAttributeKeyCount() {
      return attributeKey_.size();
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public String getAttributeKey(int index) {
      return attributeKey_.get(index);
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public com.google.protobuf.ByteString getAttributeKeyBytes(int index) {
      return attributeKey_.getByteString(index);
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public Builder setAttributeKey(int index, String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAttributeKeyIsMutable();
      attributeKey_.set(index, value);
      onChanged();
      return this;
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public Builder addAttributeKey(String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureAttributeKeyIsMutable();
      attributeKey_.add(value);
      onChanged();
      return this;
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public Builder addAllAttributeKey(Iterable<String> values) {
      ensureAttributeKeyIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(values, attributeKey_);
      onChanged();
      return this;
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public Builder clearAttributeKey() {
      attributeKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /** <code>repeated string attribute_key = 1;</code> */
    public Builder addAttributeKeyBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureAttributeKeyIsMutable();
      attributeKey_.add(value);
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.selective_disclosure.proto.AttributeTemplate)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.selective_disclosure.proto.AttributeTemplate)
  private static final AttributeTemplate DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new AttributeTemplate();
  }

  public static AttributeTemplate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AttributeTemplate> PARSER =
      new com.google.protobuf.AbstractParser<AttributeTemplate>() {
        @Override
        public AttributeTemplate parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new AttributeTemplate(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<AttributeTemplate> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AttributeTemplate> getParserForType() {
    return PARSER;
  }

  @Override
  public AttributeTemplate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
