// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

/** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.BlindedCredentialSecret} */
public final class BlindedCredentialSecret extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.selective_disclosure.proto.BlindedCredentialSecret)
    BlindedCredentialSecretOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use BlindedCredentialSecret.newBuilder() to construct.
  private BlindedCredentialSecret(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private BlindedCredentialSecret() {
    blindedCredentialSecrets_ = "";
    blindedCredentialSecretsCorrectnessProof_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new BlindedCredentialSecret();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private BlindedCredentialSecret(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              String s = input.readStringRequireUtf8();

              blindedCredentialSecrets_ = s;
              break;
            }
          case 18:
            {
              String s = input.readStringRequireUtf8();

              blindedCredentialSecretsCorrectnessProof_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_BlindedCredentialSecret_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_BlindedCredentialSecret_fieldAccessorTable
        .ensureFieldAccessorsInitialized(BlindedCredentialSecret.class, Builder.class);
  }

  public static final int BLINDED_CREDENTIAL_SECRETS_FIELD_NUMBER = 1;
  private volatile Object blindedCredentialSecrets_;
  /** <code>string blinded_credential_secrets = 1;</code> */
  public String getBlindedCredentialSecrets() {
    Object ref = blindedCredentialSecrets_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blindedCredentialSecrets_ = s;
      return s;
    }
  }
  /** <code>string blinded_credential_secrets = 1;</code> */
  public com.google.protobuf.ByteString getBlindedCredentialSecretsBytes() {
    Object ref = blindedCredentialSecrets_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      blindedCredentialSecrets_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLINDED_CREDENTIAL_SECRETS_CORRECTNESS_PROOF_FIELD_NUMBER = 2;
  private volatile Object blindedCredentialSecretsCorrectnessProof_;
  /** <code>string blinded_credential_secrets_correctness_proof = 2;</code> */
  public String getBlindedCredentialSecretsCorrectnessProof() {
    Object ref = blindedCredentialSecretsCorrectnessProof_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blindedCredentialSecretsCorrectnessProof_ = s;
      return s;
    }
  }
  /** <code>string blinded_credential_secrets_correctness_proof = 2;</code> */
  public com.google.protobuf.ByteString getBlindedCredentialSecretsCorrectnessProofBytes() {
    Object ref = blindedCredentialSecretsCorrectnessProof_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      blindedCredentialSecretsCorrectnessProof_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getBlindedCredentialSecretsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, blindedCredentialSecrets_);
    }
    if (!getBlindedCredentialSecretsCorrectnessProofBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(
          output, 2, blindedCredentialSecretsCorrectnessProof_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBlindedCredentialSecretsBytes().isEmpty()) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(1, blindedCredentialSecrets_);
    }
    if (!getBlindedCredentialSecretsCorrectnessProofBytes().isEmpty()) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(
              2, blindedCredentialSecretsCorrectnessProof_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof BlindedCredentialSecret)) {
      return super.equals(obj);
    }
    BlindedCredentialSecret other = (BlindedCredentialSecret) obj;

    if (!getBlindedCredentialSecrets().equals(other.getBlindedCredentialSecrets())) return false;
    if (!getBlindedCredentialSecretsCorrectnessProof()
        .equals(other.getBlindedCredentialSecretsCorrectnessProof())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BLINDED_CREDENTIAL_SECRETS_FIELD_NUMBER;
    hash = (53 * hash) + getBlindedCredentialSecrets().hashCode();
    hash = (37 * hash) + BLINDED_CREDENTIAL_SECRETS_CORRECTNESS_PROOF_FIELD_NUMBER;
    hash = (53 * hash) + getBlindedCredentialSecretsCorrectnessProof().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BlindedCredentialSecret parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static BlindedCredentialSecret parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static BlindedCredentialSecret parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static BlindedCredentialSecret parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static BlindedCredentialSecret parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static BlindedCredentialSecret parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static BlindedCredentialSecret parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static BlindedCredentialSecret parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static BlindedCredentialSecret parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static BlindedCredentialSecret parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static BlindedCredentialSecret parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static BlindedCredentialSecret parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(BlindedCredentialSecret prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.BlindedCredentialSecret} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.selective_disclosure.proto.BlindedCredentialSecret)
      BlindedCredentialSecretOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_BlindedCredentialSecret_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_BlindedCredentialSecret_fieldAccessorTable
          .ensureFieldAccessorsInitialized(BlindedCredentialSecret.class, Builder.class);
    }

    // Construct using
    // com.webank.wedpr.selectivedisclosure.proto.BlindedCredentialSecret.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      blindedCredentialSecrets_ = "";

      blindedCredentialSecretsCorrectnessProof_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_BlindedCredentialSecret_descriptor;
    }

    @Override
    public BlindedCredentialSecret getDefaultInstanceForType() {
      return BlindedCredentialSecret.getDefaultInstance();
    }

    @Override
    public BlindedCredentialSecret build() {
      BlindedCredentialSecret result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BlindedCredentialSecret buildPartial() {
      BlindedCredentialSecret result = new BlindedCredentialSecret(this);
      result.blindedCredentialSecrets_ = blindedCredentialSecrets_;
      result.blindedCredentialSecretsCorrectnessProof_ = blindedCredentialSecretsCorrectnessProof_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BlindedCredentialSecret) {
        return mergeFrom((BlindedCredentialSecret) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BlindedCredentialSecret other) {
      if (other == BlindedCredentialSecret.getDefaultInstance()) return this;
      if (!other.getBlindedCredentialSecrets().isEmpty()) {
        blindedCredentialSecrets_ = other.blindedCredentialSecrets_;
        onChanged();
      }
      if (!other.getBlindedCredentialSecretsCorrectnessProof().isEmpty()) {
        blindedCredentialSecretsCorrectnessProof_ = other.blindedCredentialSecretsCorrectnessProof_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      BlindedCredentialSecret parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (BlindedCredentialSecret) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object blindedCredentialSecrets_ = "";
    /** <code>string blinded_credential_secrets = 1;</code> */
    public String getBlindedCredentialSecrets() {
      Object ref = blindedCredentialSecrets_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blindedCredentialSecrets_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string blinded_credential_secrets = 1;</code> */
    public com.google.protobuf.ByteString getBlindedCredentialSecretsBytes() {
      Object ref = blindedCredentialSecrets_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        blindedCredentialSecrets_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string blinded_credential_secrets = 1;</code> */
    public Builder setBlindedCredentialSecrets(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      blindedCredentialSecrets_ = value;
      onChanged();
      return this;
    }
    /** <code>string blinded_credential_secrets = 1;</code> */
    public Builder clearBlindedCredentialSecrets() {

      blindedCredentialSecrets_ = getDefaultInstance().getBlindedCredentialSecrets();
      onChanged();
      return this;
    }
    /** <code>string blinded_credential_secrets = 1;</code> */
    public Builder setBlindedCredentialSecretsBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      blindedCredentialSecrets_ = value;
      onChanged();
      return this;
    }

    private Object blindedCredentialSecretsCorrectnessProof_ = "";
    /** <code>string blinded_credential_secrets_correctness_proof = 2;</code> */
    public String getBlindedCredentialSecretsCorrectnessProof() {
      Object ref = blindedCredentialSecretsCorrectnessProof_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blindedCredentialSecretsCorrectnessProof_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string blinded_credential_secrets_correctness_proof = 2;</code> */
    public com.google.protobuf.ByteString getBlindedCredentialSecretsCorrectnessProofBytes() {
      Object ref = blindedCredentialSecretsCorrectnessProof_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        blindedCredentialSecretsCorrectnessProof_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string blinded_credential_secrets_correctness_proof = 2;</code> */
    public Builder setBlindedCredentialSecretsCorrectnessProof(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      blindedCredentialSecretsCorrectnessProof_ = value;
      onChanged();
      return this;
    }
    /** <code>string blinded_credential_secrets_correctness_proof = 2;</code> */
    public Builder clearBlindedCredentialSecretsCorrectnessProof() {

      blindedCredentialSecretsCorrectnessProof_ =
          getDefaultInstance().getBlindedCredentialSecretsCorrectnessProof();
      onChanged();
      return this;
    }
    /** <code>string blinded_credential_secrets_correctness_proof = 2;</code> */
    public Builder setBlindedCredentialSecretsCorrectnessProofBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      blindedCredentialSecretsCorrectnessProof_ = value;
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.selective_disclosure.proto.BlindedCredentialSecret)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.selective_disclosure.proto.BlindedCredentialSecret)
  private static final BlindedCredentialSecret DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new BlindedCredentialSecret();
  }

  public static BlindedCredentialSecret getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlindedCredentialSecret> PARSER =
      new com.google.protobuf.AbstractParser<BlindedCredentialSecret>() {
        @Override
        public BlindedCredentialSecret parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlindedCredentialSecret(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<BlindedCredentialSecret> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BlindedCredentialSecret> getParserForType() {
    return PARSER;
  }

  @Override
  public BlindedCredentialSecret getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
