// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

public interface CredentialInfoOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.selective_disclosure.proto.CredentialInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attribute_pair = 1;
   * </code>
   */
  java.util.List<StringToStringPair> getAttributePairList();
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attribute_pair = 1;
   * </code>
   */
  StringToStringPair getAttributePair(int index);
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attribute_pair = 1;
   * </code>
   */
  int getAttributePairCount();
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attribute_pair = 1;
   * </code>
   */
  java.util.List<? extends StringToStringPairOrBuilder> getAttributePairOrBuilderList();
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attribute_pair = 1;
   * </code>
   */
  StringToStringPairOrBuilder getAttributePairOrBuilder(int index);
}
