// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

public interface CredentialSignatureOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.selective_disclosure.proto.CredentialSignature)
    com.google.protobuf.MessageOrBuilder {

  /** <code>string credential_signature = 1;</code> */
  String getCredentialSignature();
  /** <code>string credential_signature = 1;</code> */
  com.google.protobuf.ByteString getCredentialSignatureBytes();

  /** <code>string signature_correctness_proof = 2;</code> */
  String getSignatureCorrectnessProof();
  /** <code>string signature_correctness_proof = 2;</code> */
  com.google.protobuf.ByteString getSignatureCorrectnessProofBytes();
}
