// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

/** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.CredentialTemplate} */
public final class CredentialTemplate extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.selective_disclosure.proto.CredentialTemplate)
    CredentialTemplateOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use CredentialTemplate.newBuilder() to construct.
  private CredentialTemplate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private CredentialTemplate() {
    credentialKeyCorrectnessProof_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new CredentialTemplate();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private CredentialTemplate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              AttributeTemplate.Builder subBuilder = null;
              if (credentialSchema_ != null) {
                subBuilder = credentialSchema_.toBuilder();
              }
              credentialSchema_ = input.readMessage(AttributeTemplate.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(credentialSchema_);
                credentialSchema_ = subBuilder.buildPartial();
              }

              break;
            }
          case 18:
            {
              String s = input.readStringRequireUtf8();

              credentialKeyCorrectnessProof_ = s;
              break;
            }
          case 26:
            {
              TemplatePublicKey.Builder subBuilder = null;
              if (publicKey_ != null) {
                subBuilder = publicKey_.toBuilder();
              }
              publicKey_ = input.readMessage(TemplatePublicKey.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(publicKey_);
                publicKey_ = subBuilder.buildPartial();
              }

              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialTemplate_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialTemplate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(CredentialTemplate.class, Builder.class);
  }

  public static final int CREDENTIAL_SCHEMA_FIELD_NUMBER = 1;
  private AttributeTemplate credentialSchema_;
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
   * </code>
   */
  public boolean hasCredentialSchema() {
    return credentialSchema_ != null;
  }
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
   * </code>
   */
  public AttributeTemplate getCredentialSchema() {
    return credentialSchema_ == null ? AttributeTemplate.getDefaultInstance() : credentialSchema_;
  }
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
   * </code>
   */
  public AttributeTemplateOrBuilder getCredentialSchemaOrBuilder() {
    return getCredentialSchema();
  }

  public static final int CREDENTIAL_KEY_CORRECTNESS_PROOF_FIELD_NUMBER = 2;
  private volatile Object credentialKeyCorrectnessProof_;
  /** <code>string credential_key_correctness_proof = 2;</code> */
  public String getCredentialKeyCorrectnessProof() {
    Object ref = credentialKeyCorrectnessProof_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      credentialKeyCorrectnessProof_ = s;
      return s;
    }
  }
  /** <code>string credential_key_correctness_proof = 2;</code> */
  public com.google.protobuf.ByteString getCredentialKeyCorrectnessProofBytes() {
    Object ref = credentialKeyCorrectnessProof_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      credentialKeyCorrectnessProof_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBLIC_KEY_FIELD_NUMBER = 3;
  private TemplatePublicKey publicKey_;
  /** <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;</code> */
  public boolean hasPublicKey() {
    return publicKey_ != null;
  }
  /** <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;</code> */
  public TemplatePublicKey getPublicKey() {
    return publicKey_ == null ? TemplatePublicKey.getDefaultInstance() : publicKey_;
  }
  /** <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;</code> */
  public TemplatePublicKeyOrBuilder getPublicKeyOrBuilder() {
    return getPublicKey();
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (credentialSchema_ != null) {
      output.writeMessage(1, getCredentialSchema());
    }
    if (!getCredentialKeyCorrectnessProofBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, credentialKeyCorrectnessProof_);
    }
    if (publicKey_ != null) {
      output.writeMessage(3, getPublicKey());
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (credentialSchema_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getCredentialSchema());
    }
    if (!getCredentialKeyCorrectnessProofBytes().isEmpty()) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(
              2, credentialKeyCorrectnessProof_);
    }
    if (publicKey_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(3, getPublicKey());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof CredentialTemplate)) {
      return super.equals(obj);
    }
    CredentialTemplate other = (CredentialTemplate) obj;

    if (hasCredentialSchema() != other.hasCredentialSchema()) return false;
    if (hasCredentialSchema()) {
      if (!getCredentialSchema().equals(other.getCredentialSchema())) return false;
    }
    if (!getCredentialKeyCorrectnessProof().equals(other.getCredentialKeyCorrectnessProof()))
      return false;
    if (hasPublicKey() != other.hasPublicKey()) return false;
    if (hasPublicKey()) {
      if (!getPublicKey().equals(other.getPublicKey())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCredentialSchema()) {
      hash = (37 * hash) + CREDENTIAL_SCHEMA_FIELD_NUMBER;
      hash = (53 * hash) + getCredentialSchema().hashCode();
    }
    hash = (37 * hash) + CREDENTIAL_KEY_CORRECTNESS_PROOF_FIELD_NUMBER;
    hash = (53 * hash) + getCredentialKeyCorrectnessProof().hashCode();
    if (hasPublicKey()) {
      hash = (37 * hash) + PUBLIC_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPublicKey().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CredentialTemplate parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CredentialTemplate parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CredentialTemplate parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CredentialTemplate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CredentialTemplate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CredentialTemplate parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CredentialTemplate parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static CredentialTemplate parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static CredentialTemplate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static CredentialTemplate parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static CredentialTemplate parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static CredentialTemplate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(CredentialTemplate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.CredentialTemplate} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.selective_disclosure.proto.CredentialTemplate)
      CredentialTemplateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialTemplate_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialTemplate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(CredentialTemplate.class, Builder.class);
    }

    // Construct using
    // com.webank.wedpr.selectivedisclosure.proto.CredentialTemplate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      if (credentialSchemaBuilder_ == null) {
        credentialSchema_ = null;
      } else {
        credentialSchema_ = null;
        credentialSchemaBuilder_ = null;
      }
      credentialKeyCorrectnessProof_ = "";

      if (publicKeyBuilder_ == null) {
        publicKey_ = null;
      } else {
        publicKey_ = null;
        publicKeyBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialTemplate_descriptor;
    }

    @Override
    public CredentialTemplate getDefaultInstanceForType() {
      return CredentialTemplate.getDefaultInstance();
    }

    @Override
    public CredentialTemplate build() {
      CredentialTemplate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CredentialTemplate buildPartial() {
      CredentialTemplate result = new CredentialTemplate(this);
      if (credentialSchemaBuilder_ == null) {
        result.credentialSchema_ = credentialSchema_;
      } else {
        result.credentialSchema_ = credentialSchemaBuilder_.build();
      }
      result.credentialKeyCorrectnessProof_ = credentialKeyCorrectnessProof_;
      if (publicKeyBuilder_ == null) {
        result.publicKey_ = publicKey_;
      } else {
        result.publicKey_ = publicKeyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CredentialTemplate) {
        return mergeFrom((CredentialTemplate) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CredentialTemplate other) {
      if (other == CredentialTemplate.getDefaultInstance()) return this;
      if (other.hasCredentialSchema()) {
        mergeCredentialSchema(other.getCredentialSchema());
      }
      if (!other.getCredentialKeyCorrectnessProof().isEmpty()) {
        credentialKeyCorrectnessProof_ = other.credentialKeyCorrectnessProof_;
        onChanged();
      }
      if (other.hasPublicKey()) {
        mergePublicKey(other.getPublicKey());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CredentialTemplate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CredentialTemplate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private AttributeTemplate credentialSchema_;
    private com.google.protobuf.SingleFieldBuilderV3<
            AttributeTemplate, AttributeTemplate.Builder, AttributeTemplateOrBuilder>
        credentialSchemaBuilder_;
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    public boolean hasCredentialSchema() {
      return credentialSchemaBuilder_ != null || credentialSchema_ != null;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    public AttributeTemplate getCredentialSchema() {
      if (credentialSchemaBuilder_ == null) {
        return credentialSchema_ == null
            ? AttributeTemplate.getDefaultInstance()
            : credentialSchema_;
      } else {
        return credentialSchemaBuilder_.getMessage();
      }
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    public Builder setCredentialSchema(AttributeTemplate value) {
      if (credentialSchemaBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        credentialSchema_ = value;
        onChanged();
      } else {
        credentialSchemaBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    public Builder setCredentialSchema(AttributeTemplate.Builder builderForValue) {
      if (credentialSchemaBuilder_ == null) {
        credentialSchema_ = builderForValue.build();
        onChanged();
      } else {
        credentialSchemaBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    public Builder mergeCredentialSchema(AttributeTemplate value) {
      if (credentialSchemaBuilder_ == null) {
        if (credentialSchema_ != null) {
          credentialSchema_ =
              AttributeTemplate.newBuilder(credentialSchema_).mergeFrom(value).buildPartial();
        } else {
          credentialSchema_ = value;
        }
        onChanged();
      } else {
        credentialSchemaBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    public Builder clearCredentialSchema() {
      if (credentialSchemaBuilder_ == null) {
        credentialSchema_ = null;
        onChanged();
      } else {
        credentialSchema_ = null;
        credentialSchemaBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    public AttributeTemplate.Builder getCredentialSchemaBuilder() {

      onChanged();
      return getCredentialSchemaFieldBuilder().getBuilder();
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    public AttributeTemplateOrBuilder getCredentialSchemaOrBuilder() {
      if (credentialSchemaBuilder_ != null) {
        return credentialSchemaBuilder_.getMessageOrBuilder();
      } else {
        return credentialSchema_ == null
            ? AttributeTemplate.getDefaultInstance()
            : credentialSchema_;
      }
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            AttributeTemplate, AttributeTemplate.Builder, AttributeTemplateOrBuilder>
        getCredentialSchemaFieldBuilder() {
      if (credentialSchemaBuilder_ == null) {
        credentialSchemaBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                AttributeTemplate, AttributeTemplate.Builder, AttributeTemplateOrBuilder>(
                getCredentialSchema(), getParentForChildren(), isClean());
        credentialSchema_ = null;
      }
      return credentialSchemaBuilder_;
    }

    private Object credentialKeyCorrectnessProof_ = "";
    /** <code>string credential_key_correctness_proof = 2;</code> */
    public String getCredentialKeyCorrectnessProof() {
      Object ref = credentialKeyCorrectnessProof_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        credentialKeyCorrectnessProof_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string credential_key_correctness_proof = 2;</code> */
    public com.google.protobuf.ByteString getCredentialKeyCorrectnessProofBytes() {
      Object ref = credentialKeyCorrectnessProof_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        credentialKeyCorrectnessProof_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string credential_key_correctness_proof = 2;</code> */
    public Builder setCredentialKeyCorrectnessProof(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      credentialKeyCorrectnessProof_ = value;
      onChanged();
      return this;
    }
    /** <code>string credential_key_correctness_proof = 2;</code> */
    public Builder clearCredentialKeyCorrectnessProof() {

      credentialKeyCorrectnessProof_ = getDefaultInstance().getCredentialKeyCorrectnessProof();
      onChanged();
      return this;
    }
    /** <code>string credential_key_correctness_proof = 2;</code> */
    public Builder setCredentialKeyCorrectnessProofBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      credentialKeyCorrectnessProof_ = value;
      onChanged();
      return this;
    }

    private TemplatePublicKey publicKey_;
    private com.google.protobuf.SingleFieldBuilderV3<
            TemplatePublicKey, TemplatePublicKey.Builder, TemplatePublicKeyOrBuilder>
        publicKeyBuilder_;
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    public boolean hasPublicKey() {
      return publicKeyBuilder_ != null || publicKey_ != null;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    public TemplatePublicKey getPublicKey() {
      if (publicKeyBuilder_ == null) {
        return publicKey_ == null ? TemplatePublicKey.getDefaultInstance() : publicKey_;
      } else {
        return publicKeyBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    public Builder setPublicKey(TemplatePublicKey value) {
      if (publicKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        publicKey_ = value;
        onChanged();
      } else {
        publicKeyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    public Builder setPublicKey(TemplatePublicKey.Builder builderForValue) {
      if (publicKeyBuilder_ == null) {
        publicKey_ = builderForValue.build();
        onChanged();
      } else {
        publicKeyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    public Builder mergePublicKey(TemplatePublicKey value) {
      if (publicKeyBuilder_ == null) {
        if (publicKey_ != null) {
          publicKey_ = TemplatePublicKey.newBuilder(publicKey_).mergeFrom(value).buildPartial();
        } else {
          publicKey_ = value;
        }
        onChanged();
      } else {
        publicKeyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    public Builder clearPublicKey() {
      if (publicKeyBuilder_ == null) {
        publicKey_ = null;
        onChanged();
      } else {
        publicKey_ = null;
        publicKeyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    public TemplatePublicKey.Builder getPublicKeyBuilder() {

      onChanged();
      return getPublicKeyFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    public TemplatePublicKeyOrBuilder getPublicKeyOrBuilder() {
      if (publicKeyBuilder_ != null) {
        return publicKeyBuilder_.getMessageOrBuilder();
      } else {
        return publicKey_ == null ? TemplatePublicKey.getDefaultInstance() : publicKey_;
      }
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            TemplatePublicKey, TemplatePublicKey.Builder, TemplatePublicKeyOrBuilder>
        getPublicKeyFieldBuilder() {
      if (publicKeyBuilder_ == null) {
        publicKeyBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                TemplatePublicKey, TemplatePublicKey.Builder, TemplatePublicKeyOrBuilder>(
                getPublicKey(), getParentForChildren(), isClean());
        publicKey_ = null;
      }
      return publicKeyBuilder_;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.selective_disclosure.proto.CredentialTemplate)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.selective_disclosure.proto.CredentialTemplate)
  private static final CredentialTemplate DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new CredentialTemplate();
  }

  public static CredentialTemplate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CredentialTemplate> PARSER =
      new com.google.protobuf.AbstractParser<CredentialTemplate>() {
        @Override
        public CredentialTemplate parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CredentialTemplate(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<CredentialTemplate> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CredentialTemplate> getParserForType() {
    return PARSER;
  }

  @Override
  public CredentialTemplate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
