// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.webank.wedpr.selectivedisclosure.proto;

public interface CredentialSignatureRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.selective_disclosure.proto.CredentialSignatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;</code>
   */
  boolean hasCredentialInfo();
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;</code>
   */
  CredentialInfo getCredentialInfo();
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;</code>
   */
  CredentialInfoOrBuilder getCredentialInfoOrBuilder();

  /** <code>string blinded_credential_secrets = 2;</code> */
  String getBlindedCredentialSecrets();
  /** <code>string blinded_credential_secrets = 2;</code> */
  com.google.protobuf.ByteString getBlindedCredentialSecretsBytes();

  /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
  String getBlindedCredentialSecretsCorrectnessProof();
  /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
  com.google.protobuf.ByteString getBlindedCredentialSecretsCorrectnessProofBytes();
}
