// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.webank.wedpr.selectivedisclosure.proto;

/** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.CredentialSignatureRequest} */
public final class CredentialSignatureRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.selective_disclosure.proto.CredentialSignatureRequest)
    CredentialSignatureRequestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use CredentialSignatureRequest.newBuilder() to construct.
  private CredentialSignatureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private CredentialSignatureRequest() {
    blindedCredentialSecrets_ = "";
    blindedCredentialSecretsCorrectnessProof_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new CredentialSignatureRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private CredentialSignatureRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              CredentialInfo.Builder subBuilder = null;
              if (credentialInfo_ != null) {
                subBuilder = credentialInfo_.toBuilder();
              }
              credentialInfo_ = input.readMessage(CredentialInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(credentialInfo_);
                credentialInfo_ = subBuilder.buildPartial();
              }

              break;
            }
          case 18:
            {
              String s = input.readStringRequireUtf8();

              blindedCredentialSecrets_ = s;
              break;
            }
          case 26:
            {
              String s = input.readStringRequireUtf8();

              blindedCredentialSecretsCorrectnessProof_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return Protocol
        .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Protocol
        .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(CredentialSignatureRequest.class, Builder.class);
  }

  public static final int CREDENTIAL_INFO_FIELD_NUMBER = 1;
  private CredentialInfo credentialInfo_;
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;</code>
   */
  public boolean hasCredentialInfo() {
    return credentialInfo_ != null;
  }
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;</code>
   */
  public CredentialInfo getCredentialInfo() {
    return credentialInfo_ == null ? CredentialInfo.getDefaultInstance() : credentialInfo_;
  }
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;</code>
   */
  public CredentialInfoOrBuilder getCredentialInfoOrBuilder() {
    return getCredentialInfo();
  }

  public static final int BLINDED_CREDENTIAL_SECRETS_FIELD_NUMBER = 2;
  private volatile Object blindedCredentialSecrets_;
  /** <code>string blinded_credential_secrets = 2;</code> */
  public String getBlindedCredentialSecrets() {
    Object ref = blindedCredentialSecrets_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blindedCredentialSecrets_ = s;
      return s;
    }
  }
  /** <code>string blinded_credential_secrets = 2;</code> */
  public com.google.protobuf.ByteString getBlindedCredentialSecretsBytes() {
    Object ref = blindedCredentialSecrets_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      blindedCredentialSecrets_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLINDED_CREDENTIAL_SECRETS_CORRECTNESS_PROOF_FIELD_NUMBER = 3;
  private volatile Object blindedCredentialSecretsCorrectnessProof_;
  /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
  public String getBlindedCredentialSecretsCorrectnessProof() {
    Object ref = blindedCredentialSecretsCorrectnessProof_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      blindedCredentialSecretsCorrectnessProof_ = s;
      return s;
    }
  }
  /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
  public com.google.protobuf.ByteString getBlindedCredentialSecretsCorrectnessProofBytes() {
    Object ref = blindedCredentialSecretsCorrectnessProof_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      blindedCredentialSecretsCorrectnessProof_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (credentialInfo_ != null) {
      output.writeMessage(1, getCredentialInfo());
    }
    if (!getBlindedCredentialSecretsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, blindedCredentialSecrets_);
    }
    if (!getBlindedCredentialSecretsCorrectnessProofBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(
          output, 3, blindedCredentialSecretsCorrectnessProof_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (credentialInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getCredentialInfo());
    }
    if (!getBlindedCredentialSecretsBytes().isEmpty()) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(2, blindedCredentialSecrets_);
    }
    if (!getBlindedCredentialSecretsCorrectnessProofBytes().isEmpty()) {
      size +=
          com.google.protobuf.GeneratedMessageV3.computeStringSize(
              3, blindedCredentialSecretsCorrectnessProof_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof CredentialSignatureRequest)) {
      return super.equals(obj);
    }
    CredentialSignatureRequest other = (CredentialSignatureRequest) obj;

    if (hasCredentialInfo() != other.hasCredentialInfo()) return false;
    if (hasCredentialInfo()) {
      if (!getCredentialInfo().equals(other.getCredentialInfo())) return false;
    }
    if (!getBlindedCredentialSecrets().equals(other.getBlindedCredentialSecrets())) return false;
    if (!getBlindedCredentialSecretsCorrectnessProof()
        .equals(other.getBlindedCredentialSecretsCorrectnessProof())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCredentialInfo()) {
      hash = (37 * hash) + CREDENTIAL_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getCredentialInfo().hashCode();
    }
    hash = (37 * hash) + BLINDED_CREDENTIAL_SECRETS_FIELD_NUMBER;
    hash = (53 * hash) + getBlindedCredentialSecrets().hashCode();
    hash = (37 * hash) + BLINDED_CREDENTIAL_SECRETS_CORRECTNESS_PROOF_FIELD_NUMBER;
    hash = (53 * hash) + getBlindedCredentialSecretsCorrectnessProof().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CredentialSignatureRequest parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CredentialSignatureRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CredentialSignatureRequest parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CredentialSignatureRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CredentialSignatureRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CredentialSignatureRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CredentialSignatureRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static CredentialSignatureRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static CredentialSignatureRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static CredentialSignatureRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static CredentialSignatureRequest parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static CredentialSignatureRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(CredentialSignatureRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.CredentialSignatureRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.selective_disclosure.proto.CredentialSignatureRequest)
      CredentialSignatureRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Protocol
          .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol
          .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(CredentialSignatureRequest.class, Builder.class);
    }

    // Construct using
    // com.webank.wedpr.selectivedisclosure.proto.CredentialSignatureRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      if (credentialInfoBuilder_ == null) {
        credentialInfo_ = null;
      } else {
        credentialInfo_ = null;
        credentialInfoBuilder_ = null;
      }
      blindedCredentialSecrets_ = "";

      blindedCredentialSecretsCorrectnessProof_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Protocol
          .internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_descriptor;
    }

    @Override
    public CredentialSignatureRequest getDefaultInstanceForType() {
      return CredentialSignatureRequest.getDefaultInstance();
    }

    @Override
    public CredentialSignatureRequest build() {
      CredentialSignatureRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CredentialSignatureRequest buildPartial() {
      CredentialSignatureRequest result = new CredentialSignatureRequest(this);
      if (credentialInfoBuilder_ == null) {
        result.credentialInfo_ = credentialInfo_;
      } else {
        result.credentialInfo_ = credentialInfoBuilder_.build();
      }
      result.blindedCredentialSecrets_ = blindedCredentialSecrets_;
      result.blindedCredentialSecretsCorrectnessProof_ = blindedCredentialSecretsCorrectnessProof_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CredentialSignatureRequest) {
        return mergeFrom((CredentialSignatureRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CredentialSignatureRequest other) {
      if (other == CredentialSignatureRequest.getDefaultInstance()) return this;
      if (other.hasCredentialInfo()) {
        mergeCredentialInfo(other.getCredentialInfo());
      }
      if (!other.getBlindedCredentialSecrets().isEmpty()) {
        blindedCredentialSecrets_ = other.blindedCredentialSecrets_;
        onChanged();
      }
      if (!other.getBlindedCredentialSecretsCorrectnessProof().isEmpty()) {
        blindedCredentialSecretsCorrectnessProof_ = other.blindedCredentialSecretsCorrectnessProof_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CredentialSignatureRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CredentialSignatureRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private CredentialInfo credentialInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
            CredentialInfo, CredentialInfo.Builder, CredentialInfoOrBuilder>
        credentialInfoBuilder_;
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    public boolean hasCredentialInfo() {
      return credentialInfoBuilder_ != null || credentialInfo_ != null;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    public CredentialInfo getCredentialInfo() {
      if (credentialInfoBuilder_ == null) {
        return credentialInfo_ == null ? CredentialInfo.getDefaultInstance() : credentialInfo_;
      } else {
        return credentialInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    public Builder setCredentialInfo(CredentialInfo value) {
      if (credentialInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        credentialInfo_ = value;
        onChanged();
      } else {
        credentialInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    public Builder setCredentialInfo(CredentialInfo.Builder builderForValue) {
      if (credentialInfoBuilder_ == null) {
        credentialInfo_ = builderForValue.build();
        onChanged();
      } else {
        credentialInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    public Builder mergeCredentialInfo(CredentialInfo value) {
      if (credentialInfoBuilder_ == null) {
        if (credentialInfo_ != null) {
          credentialInfo_ =
              CredentialInfo.newBuilder(credentialInfo_).mergeFrom(value).buildPartial();
        } else {
          credentialInfo_ = value;
        }
        onChanged();
      } else {
        credentialInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    public Builder clearCredentialInfo() {
      if (credentialInfoBuilder_ == null) {
        credentialInfo_ = null;
        onChanged();
      } else {
        credentialInfo_ = null;
        credentialInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    public CredentialInfo.Builder getCredentialInfoBuilder() {

      onChanged();
      return getCredentialInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    public CredentialInfoOrBuilder getCredentialInfoOrBuilder() {
      if (credentialInfoBuilder_ != null) {
        return credentialInfoBuilder_.getMessageOrBuilder();
      } else {
        return credentialInfo_ == null ? CredentialInfo.getDefaultInstance() : credentialInfo_;
      }
    }
    /**
     * <code>.com.webank.wedpr.selective_disclosure.proto.CredentialInfo credential_info = 1;
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            CredentialInfo, CredentialInfo.Builder, CredentialInfoOrBuilder>
        getCredentialInfoFieldBuilder() {
      if (credentialInfoBuilder_ == null) {
        credentialInfoBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                CredentialInfo, CredentialInfo.Builder, CredentialInfoOrBuilder>(
                getCredentialInfo(), getParentForChildren(), isClean());
        credentialInfo_ = null;
      }
      return credentialInfoBuilder_;
    }

    private Object blindedCredentialSecrets_ = "";
    /** <code>string blinded_credential_secrets = 2;</code> */
    public String getBlindedCredentialSecrets() {
      Object ref = blindedCredentialSecrets_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blindedCredentialSecrets_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string blinded_credential_secrets = 2;</code> */
    public com.google.protobuf.ByteString getBlindedCredentialSecretsBytes() {
      Object ref = blindedCredentialSecrets_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        blindedCredentialSecrets_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string blinded_credential_secrets = 2;</code> */
    public Builder setBlindedCredentialSecrets(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      blindedCredentialSecrets_ = value;
      onChanged();
      return this;
    }
    /** <code>string blinded_credential_secrets = 2;</code> */
    public Builder clearBlindedCredentialSecrets() {

      blindedCredentialSecrets_ = getDefaultInstance().getBlindedCredentialSecrets();
      onChanged();
      return this;
    }
    /** <code>string blinded_credential_secrets = 2;</code> */
    public Builder setBlindedCredentialSecretsBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      blindedCredentialSecrets_ = value;
      onChanged();
      return this;
    }

    private Object blindedCredentialSecretsCorrectnessProof_ = "";
    /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
    public String getBlindedCredentialSecretsCorrectnessProof() {
      Object ref = blindedCredentialSecretsCorrectnessProof_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blindedCredentialSecretsCorrectnessProof_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
    public com.google.protobuf.ByteString getBlindedCredentialSecretsCorrectnessProofBytes() {
      Object ref = blindedCredentialSecretsCorrectnessProof_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        blindedCredentialSecretsCorrectnessProof_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
    public Builder setBlindedCredentialSecretsCorrectnessProof(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      blindedCredentialSecretsCorrectnessProof_ = value;
      onChanged();
      return this;
    }
    /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
    public Builder clearBlindedCredentialSecretsCorrectnessProof() {

      blindedCredentialSecretsCorrectnessProof_ =
          getDefaultInstance().getBlindedCredentialSecretsCorrectnessProof();
      onChanged();
      return this;
    }
    /** <code>string blinded_credential_secrets_correctness_proof = 3;</code> */
    public Builder setBlindedCredentialSecretsCorrectnessProofBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      blindedCredentialSecretsCorrectnessProof_ = value;
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.selective_disclosure.proto.CredentialSignatureRequest)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.selective_disclosure.proto.CredentialSignatureRequest)
  private static final CredentialSignatureRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new CredentialSignatureRequest();
  }

  public static CredentialSignatureRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CredentialSignatureRequest> PARSER =
      new com.google.protobuf.AbstractParser<CredentialSignatureRequest>() {
        @Override
        public CredentialSignatureRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new CredentialSignatureRequest(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<CredentialSignatureRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CredentialSignatureRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public CredentialSignatureRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
