// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

public interface CredentialTemplateOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.selective_disclosure.proto.CredentialTemplate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
   * </code>
   */
  boolean hasCredentialSchema();
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
   * </code>
   */
  AttributeTemplate getCredentialSchema();
  /**
   * <code>.com.webank.wedpr.selective_disclosure.proto.AttributeTemplate credential_schema = 1;
   * </code>
   */
  AttributeTemplateOrBuilder getCredentialSchemaOrBuilder();

  /** <code>string credential_key_correctness_proof = 2;</code> */
  String getCredentialKeyCorrectnessProof();
  /** <code>string credential_key_correctness_proof = 2;</code> */
  com.google.protobuf.ByteString getCredentialKeyCorrectnessProofBytes();

  /** <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;</code> */
  boolean hasPublicKey();
  /** <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;</code> */
  TemplatePublicKey getPublicKey();
  /** <code>.com.webank.wedpr.selective_disclosure.proto.TemplatePublicKey public_key = 3;</code> */
  TemplatePublicKeyOrBuilder getPublicKeyOrBuilder();
}
