// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.webank.wedpr.selectivedisclosure.proto;

public final class Protocol {
  private Protocol() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    String[] descriptorData = {
      "\n\016protocol.proto\022+com.webank.wedpr.selec"
          + "tive_disclosure.proto\032\014common.proto\"\314\001\n\032"
          + "CredentialSignatureRequest\022T\n\017credential"
          + "_info\030\001 \001(\0132;.com.webank.wedpr.selective"
          + "_disclosure.proto.CredentialInfo\022\"\n\032blin"
          + "ded_credential_secrets\030\002 \001(\t\0224\n,blinded_"
          + "credential_secrets_correctness_proof\030\003 \001"
          + "(\t\"\253\001\n\023VerificationRequest\022\\\n\023credential"
          + "_template\030\001 \001(\0132?.com.webank.wedpr.selec"
          + "tive_disclosure.proto.CredentialTemplate"
          + "\022\032\n\022verification_proof\030\002 \001(\t\022\032\n\022verifica"
          + "tion_nonce\030\003 \001(\tB.\n*com.webank.wedpr.sel"
          + "ectivedisclosure.protoP\001b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              Common.getDescriptor(),
            });
    internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_webank_wedpr_selective_disclosure_proto_CredentialSignatureRequest_descriptor,
            new String[] {
              "CredentialInfo",
              "BlindedCredentialSecrets",
              "BlindedCredentialSecretsCorrectnessProof",
            });
    internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_descriptor,
            new String[] {
              "CredentialTemplate", "VerificationProof", "VerificationNonce",
            });
    Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
