// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

public interface RevealedAttributeInfoOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.selective_disclosure.proto.RevealedAttributeInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attr = 1;
   * </code>
   */
  java.util.List<StringToStringPair> getAttrList();
  /**
   * <code>repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attr = 1;
   * </code>
   */
  StringToStringPair getAttr(int index);
  /**
   * <code>repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attr = 1;
   * </code>
   */
  int getAttrCount();
  /**
   * <code>repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attr = 1;
   * </code>
   */
  java.util.List<? extends StringToStringPairOrBuilder> getAttrOrBuilderList();
  /**
   * <code>repeated .com.webank.wedpr.selective_disclosure.proto.StringToStringPair attr = 1;
   * </code>
   */
  StringToStringPairOrBuilder getAttrOrBuilder(int index);
}
