// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

public interface TemplateSecretKeyOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.selective_disclosure.proto.TemplateSecretKey)
    com.google.protobuf.MessageOrBuilder {

  /** <code>string credential_secret_key = 1;</code> */
  String getCredentialSecretKey();
  /** <code>string credential_secret_key = 1;</code> */
  com.google.protobuf.ByteString getCredentialSecretKeyBytes();
}
