// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

/** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.TemplateSecretKey} */
public final class TemplateSecretKey extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.selective_disclosure.proto.TemplateSecretKey)
    TemplateSecretKeyOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use TemplateSecretKey.newBuilder() to construct.
  private TemplateSecretKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private TemplateSecretKey() {
    credentialSecretKey_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new TemplateSecretKey();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private TemplateSecretKey(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              String s = input.readStringRequireUtf8();

              credentialSecretKey_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_TemplateSecretKey_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_TemplateSecretKey_fieldAccessorTable
        .ensureFieldAccessorsInitialized(TemplateSecretKey.class, Builder.class);
  }

  public static final int CREDENTIAL_SECRET_KEY_FIELD_NUMBER = 1;
  private volatile Object credentialSecretKey_;
  /** <code>string credential_secret_key = 1;</code> */
  public String getCredentialSecretKey() {
    Object ref = credentialSecretKey_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      credentialSecretKey_ = s;
      return s;
    }
  }
  /** <code>string credential_secret_key = 1;</code> */
  public com.google.protobuf.ByteString getCredentialSecretKeyBytes() {
    Object ref = credentialSecretKey_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      credentialSecretKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getCredentialSecretKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, credentialSecretKey_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCredentialSecretKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, credentialSecretKey_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof TemplateSecretKey)) {
      return super.equals(obj);
    }
    TemplateSecretKey other = (TemplateSecretKey) obj;

    if (!getCredentialSecretKey().equals(other.getCredentialSecretKey())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CREDENTIAL_SECRET_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getCredentialSecretKey().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TemplateSecretKey parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static TemplateSecretKey parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static TemplateSecretKey parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static TemplateSecretKey parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static TemplateSecretKey parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static TemplateSecretKey parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static TemplateSecretKey parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static TemplateSecretKey parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static TemplateSecretKey parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static TemplateSecretKey parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static TemplateSecretKey parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static TemplateSecretKey parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(TemplateSecretKey prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.TemplateSecretKey} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.selective_disclosure.proto.TemplateSecretKey)
      TemplateSecretKeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_TemplateSecretKey_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_TemplateSecretKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(TemplateSecretKey.class, Builder.class);
    }

    // Construct using com.webank.wedpr.selectivedisclosure.proto.TemplateSecretKey.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      credentialSecretKey_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_TemplateSecretKey_descriptor;
    }

    @Override
    public TemplateSecretKey getDefaultInstanceForType() {
      return TemplateSecretKey.getDefaultInstance();
    }

    @Override
    public TemplateSecretKey build() {
      TemplateSecretKey result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TemplateSecretKey buildPartial() {
      TemplateSecretKey result = new TemplateSecretKey(this);
      result.credentialSecretKey_ = credentialSecretKey_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TemplateSecretKey) {
        return mergeFrom((TemplateSecretKey) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TemplateSecretKey other) {
      if (other == TemplateSecretKey.getDefaultInstance()) return this;
      if (!other.getCredentialSecretKey().isEmpty()) {
        credentialSecretKey_ = other.credentialSecretKey_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TemplateSecretKey parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TemplateSecretKey) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object credentialSecretKey_ = "";
    /** <code>string credential_secret_key = 1;</code> */
    public String getCredentialSecretKey() {
      Object ref = credentialSecretKey_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        credentialSecretKey_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string credential_secret_key = 1;</code> */
    public com.google.protobuf.ByteString getCredentialSecretKeyBytes() {
      Object ref = credentialSecretKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        credentialSecretKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string credential_secret_key = 1;</code> */
    public Builder setCredentialSecretKey(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      credentialSecretKey_ = value;
      onChanged();
      return this;
    }
    /** <code>string credential_secret_key = 1;</code> */
    public Builder clearCredentialSecretKey() {

      credentialSecretKey_ = getDefaultInstance().getCredentialSecretKey();
      onChanged();
      return this;
    }
    /** <code>string credential_secret_key = 1;</code> */
    public Builder setCredentialSecretKeyBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      credentialSecretKey_ = value;
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.selective_disclosure.proto.TemplateSecretKey)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.selective_disclosure.proto.TemplateSecretKey)
  private static final TemplateSecretKey DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new TemplateSecretKey();
  }

  public static TemplateSecretKey getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TemplateSecretKey> PARSER =
      new com.google.protobuf.AbstractParser<TemplateSecretKey>() {
        @Override
        public TemplateSecretKey parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new TemplateSecretKey(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<TemplateSecretKey> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TemplateSecretKey> getParserForType() {
    return PARSER;
  }

  @Override
  public TemplateSecretKey getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
