// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

/** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.VerificationRule} */
public final class VerificationRule extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.selective_disclosure.proto.VerificationRule)
    VerificationRuleOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use VerificationRule.newBuilder() to construct.
  private VerificationRule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private VerificationRule() {
    revealedAttribute_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    predicateAttribute_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new VerificationRule();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private VerificationRule(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                revealedAttribute_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              revealedAttribute_.add(s);
              break;
            }
          case 18:
            {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                predicateAttribute_ = new java.util.ArrayList<Predicate>();
                mutable_bitField0_ |= 0x00000002;
              }
              predicateAttribute_.add(input.readMessage(Predicate.parser(), extensionRegistry));
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        revealedAttribute_ = revealedAttribute_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        predicateAttribute_ = java.util.Collections.unmodifiableList(predicateAttribute_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRule_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Common
        .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRule_fieldAccessorTable
        .ensureFieldAccessorsInitialized(VerificationRule.class, Builder.class);
  }

  public static final int REVEALED_ATTRIBUTE_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList revealedAttribute_;
  /** <code>repeated string revealed_attribute = 1;</code> */
  public com.google.protobuf.ProtocolStringList getRevealedAttributeList() {
    return revealedAttribute_;
  }
  /** <code>repeated string revealed_attribute = 1;</code> */
  public int getRevealedAttributeCount() {
    return revealedAttribute_.size();
  }
  /** <code>repeated string revealed_attribute = 1;</code> */
  public String getRevealedAttribute(int index) {
    return revealedAttribute_.get(index);
  }
  /** <code>repeated string revealed_attribute = 1;</code> */
  public com.google.protobuf.ByteString getRevealedAttributeBytes(int index) {
    return revealedAttribute_.getByteString(index);
  }

  public static final int PREDICATE_ATTRIBUTE_FIELD_NUMBER = 2;
  private java.util.List<Predicate> predicateAttribute_;
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  public java.util.List<Predicate> getPredicateAttributeList() {
    return predicateAttribute_;
  }
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  public java.util.List<? extends PredicateOrBuilder> getPredicateAttributeOrBuilderList() {
    return predicateAttribute_;
  }
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  public int getPredicateAttributeCount() {
    return predicateAttribute_.size();
  }
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  public Predicate getPredicateAttribute(int index) {
    return predicateAttribute_.get(index);
  }
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  public PredicateOrBuilder getPredicateAttributeOrBuilder(int index) {
    return predicateAttribute_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    for (int i = 0; i < revealedAttribute_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, revealedAttribute_.getRaw(i));
    }
    for (int i = 0; i < predicateAttribute_.size(); i++) {
      output.writeMessage(2, predicateAttribute_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < revealedAttribute_.size(); i++) {
        dataSize += computeStringSizeNoTag(revealedAttribute_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRevealedAttributeList().size();
    }
    for (int i = 0; i < predicateAttribute_.size(); i++) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(2, predicateAttribute_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof VerificationRule)) {
      return super.equals(obj);
    }
    VerificationRule other = (VerificationRule) obj;

    if (!getRevealedAttributeList().equals(other.getRevealedAttributeList())) return false;
    if (!getPredicateAttributeList().equals(other.getPredicateAttributeList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRevealedAttributeCount() > 0) {
      hash = (37 * hash) + REVEALED_ATTRIBUTE_FIELD_NUMBER;
      hash = (53 * hash) + getRevealedAttributeList().hashCode();
    }
    if (getPredicateAttributeCount() > 0) {
      hash = (37 * hash) + PREDICATE_ATTRIBUTE_FIELD_NUMBER;
      hash = (53 * hash) + getPredicateAttributeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VerificationRule parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static VerificationRule parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static VerificationRule parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static VerificationRule parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static VerificationRule parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static VerificationRule parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static VerificationRule parseFrom(java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static VerificationRule parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static VerificationRule parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static VerificationRule parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static VerificationRule parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static VerificationRule parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(VerificationRule prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.VerificationRule} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.selective_disclosure.proto.VerificationRule)
      VerificationRuleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRule_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(VerificationRule.class, Builder.class);
    }

    // Construct using com.webank.wedpr.selectivedisclosure.proto.VerificationRule.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        getPredicateAttributeFieldBuilder();
      }
    }

    @Override
    public Builder clear() {
      super.clear();
      revealedAttribute_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (predicateAttributeBuilder_ == null) {
        predicateAttribute_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        predicateAttributeBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Common
          .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRule_descriptor;
    }

    @Override
    public VerificationRule getDefaultInstanceForType() {
      return VerificationRule.getDefaultInstance();
    }

    @Override
    public VerificationRule build() {
      VerificationRule result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VerificationRule buildPartial() {
      VerificationRule result = new VerificationRule(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        revealedAttribute_ = revealedAttribute_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.revealedAttribute_ = revealedAttribute_;
      if (predicateAttributeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          predicateAttribute_ = java.util.Collections.unmodifiableList(predicateAttribute_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.predicateAttribute_ = predicateAttribute_;
      } else {
        result.predicateAttribute_ = predicateAttributeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VerificationRule) {
        return mergeFrom((VerificationRule) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VerificationRule other) {
      if (other == VerificationRule.getDefaultInstance()) return this;
      if (!other.revealedAttribute_.isEmpty()) {
        if (revealedAttribute_.isEmpty()) {
          revealedAttribute_ = other.revealedAttribute_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRevealedAttributeIsMutable();
          revealedAttribute_.addAll(other.revealedAttribute_);
        }
        onChanged();
      }
      if (predicateAttributeBuilder_ == null) {
        if (!other.predicateAttribute_.isEmpty()) {
          if (predicateAttribute_.isEmpty()) {
            predicateAttribute_ = other.predicateAttribute_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePredicateAttributeIsMutable();
            predicateAttribute_.addAll(other.predicateAttribute_);
          }
          onChanged();
        }
      } else {
        if (!other.predicateAttribute_.isEmpty()) {
          if (predicateAttributeBuilder_.isEmpty()) {
            predicateAttributeBuilder_.dispose();
            predicateAttributeBuilder_ = null;
            predicateAttribute_ = other.predicateAttribute_;
            bitField0_ = (bitField0_ & ~0x00000002);
            predicateAttributeBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                    ? getPredicateAttributeFieldBuilder()
                    : null;
          } else {
            predicateAttributeBuilder_.addAllMessages(other.predicateAttribute_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VerificationRule parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VerificationRule) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.LazyStringList revealedAttribute_ =
        com.google.protobuf.LazyStringArrayList.EMPTY;

    private void ensureRevealedAttributeIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        revealedAttribute_ = new com.google.protobuf.LazyStringArrayList(revealedAttribute_);
        bitField0_ |= 0x00000001;
      }
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public com.google.protobuf.ProtocolStringList getRevealedAttributeList() {
      return revealedAttribute_.getUnmodifiableView();
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public int getRevealedAttributeCount() {
      return revealedAttribute_.size();
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public String getRevealedAttribute(int index) {
      return revealedAttribute_.get(index);
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public com.google.protobuf.ByteString getRevealedAttributeBytes(int index) {
      return revealedAttribute_.getByteString(index);
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public Builder setRevealedAttribute(int index, String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRevealedAttributeIsMutable();
      revealedAttribute_.set(index, value);
      onChanged();
      return this;
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public Builder addRevealedAttribute(String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRevealedAttributeIsMutable();
      revealedAttribute_.add(value);
      onChanged();
      return this;
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public Builder addAllRevealedAttribute(Iterable<String> values) {
      ensureRevealedAttributeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(values, revealedAttribute_);
      onChanged();
      return this;
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public Builder clearRevealedAttribute() {
      revealedAttribute_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /** <code>repeated string revealed_attribute = 1;</code> */
    public Builder addRevealedAttributeBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureRevealedAttributeIsMutable();
      revealedAttribute_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<Predicate> predicateAttribute_ = java.util.Collections.emptyList();

    private void ensurePredicateAttributeIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        predicateAttribute_ = new java.util.ArrayList<Predicate>(predicateAttribute_);
        bitField0_ |= 0x00000002;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Predicate, Predicate.Builder, PredicateOrBuilder>
        predicateAttributeBuilder_;

    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public java.util.List<Predicate> getPredicateAttributeList() {
      if (predicateAttributeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(predicateAttribute_);
      } else {
        return predicateAttributeBuilder_.getMessageList();
      }
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public int getPredicateAttributeCount() {
      if (predicateAttributeBuilder_ == null) {
        return predicateAttribute_.size();
      } else {
        return predicateAttributeBuilder_.getCount();
      }
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Predicate getPredicateAttribute(int index) {
      if (predicateAttributeBuilder_ == null) {
        return predicateAttribute_.get(index);
      } else {
        return predicateAttributeBuilder_.getMessage(index);
      }
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder setPredicateAttribute(int index, Predicate value) {
      if (predicateAttributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredicateAttributeIsMutable();
        predicateAttribute_.set(index, value);
        onChanged();
      } else {
        predicateAttributeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder setPredicateAttribute(int index, Predicate.Builder builderForValue) {
      if (predicateAttributeBuilder_ == null) {
        ensurePredicateAttributeIsMutable();
        predicateAttribute_.set(index, builderForValue.build());
        onChanged();
      } else {
        predicateAttributeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder addPredicateAttribute(Predicate value) {
      if (predicateAttributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredicateAttributeIsMutable();
        predicateAttribute_.add(value);
        onChanged();
      } else {
        predicateAttributeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder addPredicateAttribute(int index, Predicate value) {
      if (predicateAttributeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePredicateAttributeIsMutable();
        predicateAttribute_.add(index, value);
        onChanged();
      } else {
        predicateAttributeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder addPredicateAttribute(Predicate.Builder builderForValue) {
      if (predicateAttributeBuilder_ == null) {
        ensurePredicateAttributeIsMutable();
        predicateAttribute_.add(builderForValue.build());
        onChanged();
      } else {
        predicateAttributeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder addPredicateAttribute(int index, Predicate.Builder builderForValue) {
      if (predicateAttributeBuilder_ == null) {
        ensurePredicateAttributeIsMutable();
        predicateAttribute_.add(index, builderForValue.build());
        onChanged();
      } else {
        predicateAttributeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder addAllPredicateAttribute(Iterable<? extends Predicate> values) {
      if (predicateAttributeBuilder_ == null) {
        ensurePredicateAttributeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, predicateAttribute_);
        onChanged();
      } else {
        predicateAttributeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder clearPredicateAttribute() {
      if (predicateAttributeBuilder_ == null) {
        predicateAttribute_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        predicateAttributeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Builder removePredicateAttribute(int index) {
      if (predicateAttributeBuilder_ == null) {
        ensurePredicateAttributeIsMutable();
        predicateAttribute_.remove(index);
        onChanged();
      } else {
        predicateAttributeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Predicate.Builder getPredicateAttributeBuilder(int index) {
      return getPredicateAttributeFieldBuilder().getBuilder(index);
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public PredicateOrBuilder getPredicateAttributeOrBuilder(int index) {
      if (predicateAttributeBuilder_ == null) {
        return predicateAttribute_.get(index);
      } else {
        return predicateAttributeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public java.util.List<? extends PredicateOrBuilder> getPredicateAttributeOrBuilderList() {
      if (predicateAttributeBuilder_ != null) {
        return predicateAttributeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(predicateAttribute_);
      }
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Predicate.Builder addPredicateAttributeBuilder() {
      return getPredicateAttributeFieldBuilder().addBuilder(Predicate.getDefaultInstance());
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public Predicate.Builder addPredicateAttributeBuilder(int index) {
      return getPredicateAttributeFieldBuilder().addBuilder(index, Predicate.getDefaultInstance());
    }
    /**
     * <code>
     * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
     * </code>
     */
    public java.util.List<Predicate.Builder> getPredicateAttributeBuilderList() {
      return getPredicateAttributeFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Predicate, Predicate.Builder, PredicateOrBuilder>
        getPredicateAttributeFieldBuilder() {
      if (predicateAttributeBuilder_ == null) {
        predicateAttributeBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<
                Predicate, Predicate.Builder, PredicateOrBuilder>(
                predicateAttribute_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        predicateAttribute_ = null;
      }
      return predicateAttributeBuilder_;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.selective_disclosure.proto.VerificationRule)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.selective_disclosure.proto.VerificationRule)
  private static final VerificationRule DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new VerificationRule();
  }

  public static VerificationRule getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerificationRule> PARSER =
      new com.google.protobuf.AbstractParser<VerificationRule>() {
        @Override
        public VerificationRule parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new VerificationRule(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<VerificationRule> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VerificationRule> getParserForType() {
    return PARSER;
  }

  @Override
  public VerificationRule getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
