// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package com.webank.wedpr.selectivedisclosure.proto;

public interface VerificationRuleOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.selective_disclosure.proto.VerificationRule)
    com.google.protobuf.MessageOrBuilder {

  /** <code>repeated string revealed_attribute = 1;</code> */
  java.util.List<String> getRevealedAttributeList();
  /** <code>repeated string revealed_attribute = 1;</code> */
  int getRevealedAttributeCount();
  /** <code>repeated string revealed_attribute = 1;</code> */
  String getRevealedAttribute(int index);
  /** <code>repeated string revealed_attribute = 1;</code> */
  com.google.protobuf.ByteString getRevealedAttributeBytes(int index);

  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  java.util.List<Predicate> getPredicateAttributeList();
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  Predicate getPredicateAttribute(int index);
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  int getPredicateAttributeCount();
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  java.util.List<? extends PredicateOrBuilder> getPredicateAttributeOrBuilderList();
  /**
   * <code>
   * repeated .com.webank.wedpr.selective_disclosure.proto.Predicate predicate_attribute = 2;
   * </code>
   */
  PredicateOrBuilder getPredicateAttributeOrBuilder(int index);
}
