// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.webank.wedpr.selectivedisclosure.proto;

/** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.VerificationRequest} */
public final class VerificationRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.selective_disclosure.proto.VerificationRequest)
    VerificationRequestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use VerificationRequest.newBuilder() to construct.
  private VerificationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private VerificationRequest() {
    verificationProof_ = "";
    verificationNonce_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new VerificationRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private VerificationRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              CredentialTemplate.Builder subBuilder = null;
              if (credentialTemplate_ != null) {
                subBuilder = credentialTemplate_.toBuilder();
              }
              credentialTemplate_ =
                  input.readMessage(CredentialTemplate.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(credentialTemplate_);
                credentialTemplate_ = subBuilder.buildPartial();
              }

              break;
            }
          case 18:
            {
              String s = input.readStringRequireUtf8();

              verificationProof_ = s;
              break;
            }
          case 26:
            {
              String s = input.readStringRequireUtf8();

              verificationNonce_ = s;
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return Protocol
        .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Protocol
        .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(VerificationRequest.class, Builder.class);
  }

  public static final int CREDENTIAL_TEMPLATE_FIELD_NUMBER = 1;
  private CredentialTemplate credentialTemplate_;
  /**
   * <code>
   * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
   * </code>
   */
  public boolean hasCredentialTemplate() {
    return credentialTemplate_ != null;
  }
  /**
   * <code>
   * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
   * </code>
   */
  public CredentialTemplate getCredentialTemplate() {
    return credentialTemplate_ == null
        ? CredentialTemplate.getDefaultInstance()
        : credentialTemplate_;
  }
  /**
   * <code>
   * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
   * </code>
   */
  public CredentialTemplateOrBuilder getCredentialTemplateOrBuilder() {
    return getCredentialTemplate();
  }

  public static final int VERIFICATION_PROOF_FIELD_NUMBER = 2;
  private volatile Object verificationProof_;
  /** <code>string verification_proof = 2;</code> */
  public String getVerificationProof() {
    Object ref = verificationProof_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      verificationProof_ = s;
      return s;
    }
  }
  /** <code>string verification_proof = 2;</code> */
  public com.google.protobuf.ByteString getVerificationProofBytes() {
    Object ref = verificationProof_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      verificationProof_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFICATION_NONCE_FIELD_NUMBER = 3;
  private volatile Object verificationNonce_;
  /** <code>string verification_nonce = 3;</code> */
  public String getVerificationNonce() {
    Object ref = verificationNonce_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      verificationNonce_ = s;
      return s;
    }
  }
  /** <code>string verification_nonce = 3;</code> */
  public com.google.protobuf.ByteString getVerificationNonceBytes() {
    Object ref = verificationNonce_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((String) ref);
      verificationNonce_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (credentialTemplate_ != null) {
      output.writeMessage(1, getCredentialTemplate());
    }
    if (!getVerificationProofBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, verificationProof_);
    }
    if (!getVerificationNonceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, verificationNonce_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (credentialTemplate_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getCredentialTemplate());
    }
    if (!getVerificationProofBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, verificationProof_);
    }
    if (!getVerificationNonceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, verificationNonce_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof VerificationRequest)) {
      return super.equals(obj);
    }
    VerificationRequest other = (VerificationRequest) obj;

    if (hasCredentialTemplate() != other.hasCredentialTemplate()) return false;
    if (hasCredentialTemplate()) {
      if (!getCredentialTemplate().equals(other.getCredentialTemplate())) return false;
    }
    if (!getVerificationProof().equals(other.getVerificationProof())) return false;
    if (!getVerificationNonce().equals(other.getVerificationNonce())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCredentialTemplate()) {
      hash = (37 * hash) + CREDENTIAL_TEMPLATE_FIELD_NUMBER;
      hash = (53 * hash) + getCredentialTemplate().hashCode();
    }
    hash = (37 * hash) + VERIFICATION_PROOF_FIELD_NUMBER;
    hash = (53 * hash) + getVerificationProof().hashCode();
    hash = (37 * hash) + VERIFICATION_NONCE_FIELD_NUMBER;
    hash = (53 * hash) + getVerificationNonce().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static VerificationRequest parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static VerificationRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static VerificationRequest parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static VerificationRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static VerificationRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static VerificationRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static VerificationRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static VerificationRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static VerificationRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static VerificationRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static VerificationRequest parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static VerificationRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(VerificationRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /** Protobuf type {@code com.webank.wedpr.selective_disclosure.proto.VerificationRequest} */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.selective_disclosure.proto.VerificationRequest)
      VerificationRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return Protocol
          .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Protocol
          .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(VerificationRequest.class, Builder.class);
    }

    // Construct using
    // com.webank.wedpr.selectivedisclosure.proto.VerificationRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @Override
    public Builder clear() {
      super.clear();
      if (credentialTemplateBuilder_ == null) {
        credentialTemplate_ = null;
      } else {
        credentialTemplate_ = null;
        credentialTemplateBuilder_ = null;
      }
      verificationProof_ = "";

      verificationNonce_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return Protocol
          .internal_static_com_webank_wedpr_selective_disclosure_proto_VerificationRequest_descriptor;
    }

    @Override
    public VerificationRequest getDefaultInstanceForType() {
      return VerificationRequest.getDefaultInstance();
    }

    @Override
    public VerificationRequest build() {
      VerificationRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public VerificationRequest buildPartial() {
      VerificationRequest result = new VerificationRequest(this);
      if (credentialTemplateBuilder_ == null) {
        result.credentialTemplate_ = credentialTemplate_;
      } else {
        result.credentialTemplate_ = credentialTemplateBuilder_.build();
      }
      result.verificationProof_ = verificationProof_;
      result.verificationNonce_ = verificationNonce_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof VerificationRequest) {
        return mergeFrom((VerificationRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(VerificationRequest other) {
      if (other == VerificationRequest.getDefaultInstance()) return this;
      if (other.hasCredentialTemplate()) {
        mergeCredentialTemplate(other.getCredentialTemplate());
      }
      if (!other.getVerificationProof().isEmpty()) {
        verificationProof_ = other.verificationProof_;
        onChanged();
      }
      if (!other.getVerificationNonce().isEmpty()) {
        verificationNonce_ = other.verificationNonce_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      VerificationRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (VerificationRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private CredentialTemplate credentialTemplate_;
    private com.google.protobuf.SingleFieldBuilderV3<
            CredentialTemplate, CredentialTemplate.Builder, CredentialTemplateOrBuilder>
        credentialTemplateBuilder_;
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    public boolean hasCredentialTemplate() {
      return credentialTemplateBuilder_ != null || credentialTemplate_ != null;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    public CredentialTemplate getCredentialTemplate() {
      if (credentialTemplateBuilder_ == null) {
        return credentialTemplate_ == null
            ? CredentialTemplate.getDefaultInstance()
            : credentialTemplate_;
      } else {
        return credentialTemplateBuilder_.getMessage();
      }
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    public Builder setCredentialTemplate(CredentialTemplate value) {
      if (credentialTemplateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        credentialTemplate_ = value;
        onChanged();
      } else {
        credentialTemplateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    public Builder setCredentialTemplate(CredentialTemplate.Builder builderForValue) {
      if (credentialTemplateBuilder_ == null) {
        credentialTemplate_ = builderForValue.build();
        onChanged();
      } else {
        credentialTemplateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    public Builder mergeCredentialTemplate(CredentialTemplate value) {
      if (credentialTemplateBuilder_ == null) {
        if (credentialTemplate_ != null) {
          credentialTemplate_ =
              CredentialTemplate.newBuilder(credentialTemplate_).mergeFrom(value).buildPartial();
        } else {
          credentialTemplate_ = value;
        }
        onChanged();
      } else {
        credentialTemplateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    public Builder clearCredentialTemplate() {
      if (credentialTemplateBuilder_ == null) {
        credentialTemplate_ = null;
        onChanged();
      } else {
        credentialTemplate_ = null;
        credentialTemplateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    public CredentialTemplate.Builder getCredentialTemplateBuilder() {

      onChanged();
      return getCredentialTemplateFieldBuilder().getBuilder();
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    public CredentialTemplateOrBuilder getCredentialTemplateOrBuilder() {
      if (credentialTemplateBuilder_ != null) {
        return credentialTemplateBuilder_.getMessageOrBuilder();
      } else {
        return credentialTemplate_ == null
            ? CredentialTemplate.getDefaultInstance()
            : credentialTemplate_;
      }
    }
    /**
     * <code>
     * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
     * </code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            CredentialTemplate, CredentialTemplate.Builder, CredentialTemplateOrBuilder>
        getCredentialTemplateFieldBuilder() {
      if (credentialTemplateBuilder_ == null) {
        credentialTemplateBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                CredentialTemplate, CredentialTemplate.Builder, CredentialTemplateOrBuilder>(
                getCredentialTemplate(), getParentForChildren(), isClean());
        credentialTemplate_ = null;
      }
      return credentialTemplateBuilder_;
    }

    private Object verificationProof_ = "";
    /** <code>string verification_proof = 2;</code> */
    public String getVerificationProof() {
      Object ref = verificationProof_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        verificationProof_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string verification_proof = 2;</code> */
    public com.google.protobuf.ByteString getVerificationProofBytes() {
      Object ref = verificationProof_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        verificationProof_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string verification_proof = 2;</code> */
    public Builder setVerificationProof(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      verificationProof_ = value;
      onChanged();
      return this;
    }
    /** <code>string verification_proof = 2;</code> */
    public Builder clearVerificationProof() {

      verificationProof_ = getDefaultInstance().getVerificationProof();
      onChanged();
      return this;
    }
    /** <code>string verification_proof = 2;</code> */
    public Builder setVerificationProofBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      verificationProof_ = value;
      onChanged();
      return this;
    }

    private Object verificationNonce_ = "";
    /** <code>string verification_nonce = 3;</code> */
    public String getVerificationNonce() {
      Object ref = verificationNonce_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        verificationNonce_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /** <code>string verification_nonce = 3;</code> */
    public com.google.protobuf.ByteString getVerificationNonceBytes() {
      Object ref = verificationNonce_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        verificationNonce_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /** <code>string verification_nonce = 3;</code> */
    public Builder setVerificationNonce(String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      verificationNonce_ = value;
      onChanged();
      return this;
    }
    /** <code>string verification_nonce = 3;</code> */
    public Builder clearVerificationNonce() {

      verificationNonce_ = getDefaultInstance().getVerificationNonce();
      onChanged();
      return this;
    }
    /** <code>string verification_nonce = 3;</code> */
    public Builder setVerificationNonceBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      verificationNonce_ = value;
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.selective_disclosure.proto.VerificationRequest)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.selective_disclosure.proto.VerificationRequest)
  private static final VerificationRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new VerificationRequest();
  }

  public static VerificationRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerificationRequest> PARSER =
      new com.google.protobuf.AbstractParser<VerificationRequest>() {
        @Override
        public VerificationRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new VerificationRequest(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<VerificationRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VerificationRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public VerificationRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
