// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.webank.wedpr.selectivedisclosure.proto;

public interface VerificationRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:com.webank.wedpr.selective_disclosure.proto.VerificationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>
   * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
   * </code>
   */
  boolean hasCredentialTemplate();
  /**
   * <code>
   * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
   * </code>
   */
  CredentialTemplate getCredentialTemplate();
  /**
   * <code>
   * .com.webank.wedpr.selective_disclosure.proto.CredentialTemplate credential_template = 1;
   * </code>
   */
  CredentialTemplateOrBuilder getCredentialTemplateOrBuilder();

  /** <code>string verification_proof = 2;</code> */
  String getVerificationProof();
  /** <code>string verification_proof = 2;</code> */
  com.google.protobuf.ByteString getVerificationProofBytes();

  /** <code>string verification_nonce = 3;</code> */
  String getVerificationNonce();
  /** <code>string verification_nonce = 3;</code> */
  com.google.protobuf.ByteString getVerificationNonceBytes();
}
