// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

/**
 *
 *
 * <pre>
 * Verification rule set.
 * </pre>
 *
 * Protobuf type {@code com.webank.wedpr.scd.proto.VerificationRuleSet}
 */
public final class VerificationRuleSet extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:com.webank.wedpr.scd.proto.VerificationRuleSet)
    VerificationRuleSetOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use VerificationRuleSet.newBuilder() to construct.
  private VerificationRuleSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private VerificationRuleSet() {
    revealedAttributeName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    attributePredicate_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(UnusedPrivateParameter unused) {
    return new VerificationRuleSet();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private VerificationRuleSet(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                revealedAttributeName_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              revealedAttributeName_.add(s);
              break;
            }
          case 18:
            {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                attributePredicate_ =
                    new java.util.ArrayList<com.webank.wedpr.scd.proto.Predicate>();
                mutable_bitField0_ |= 0x00000002;
              }
              attributePredicate_.add(
                  input.readMessage(
                      com.webank.wedpr.scd.proto.Predicate.parser(), extensionRegistry));
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        revealedAttributeName_ = revealedAttributeName_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        attributePredicate_ = java.util.Collections.unmodifiableList(attributePredicate_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.webank.wedpr.scd.proto.Scd
        .internal_static_com_webank_wedpr_scd_proto_VerificationRuleSet_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return com.webank.wedpr.scd.proto.Scd
        .internal_static_com_webank_wedpr_scd_proto_VerificationRuleSet_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.webank.wedpr.scd.proto.VerificationRuleSet.class,
            com.webank.wedpr.scd.proto.VerificationRuleSet.Builder.class);
  }

  public static final int REVEALED_ATTRIBUTE_NAME_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList revealedAttributeName_;
  /** <code>repeated string revealed_attribute_name = 1;</code> */
  public com.google.protobuf.ProtocolStringList getRevealedAttributeNameList() {
    return revealedAttributeName_;
  }
  /** <code>repeated string revealed_attribute_name = 1;</code> */
  public int getRevealedAttributeNameCount() {
    return revealedAttributeName_.size();
  }
  /** <code>repeated string revealed_attribute_name = 1;</code> */
  public String getRevealedAttributeName(int index) {
    return revealedAttributeName_.get(index);
  }
  /** <code>repeated string revealed_attribute_name = 1;</code> */
  public com.google.protobuf.ByteString getRevealedAttributeNameBytes(int index) {
    return revealedAttributeName_.getByteString(index);
  }

  public static final int ATTRIBUTE_PREDICATE_FIELD_NUMBER = 2;
  private java.util.List<com.webank.wedpr.scd.proto.Predicate> attributePredicate_;
  /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
  public java.util.List<com.webank.wedpr.scd.proto.Predicate> getAttributePredicateList() {
    return attributePredicate_;
  }
  /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
  public java.util.List<? extends com.webank.wedpr.scd.proto.PredicateOrBuilder>
      getAttributePredicateOrBuilderList() {
    return attributePredicate_;
  }
  /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
  public int getAttributePredicateCount() {
    return attributePredicate_.size();
  }
  /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
  public com.webank.wedpr.scd.proto.Predicate getAttributePredicate(int index) {
    return attributePredicate_.get(index);
  }
  /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
  public com.webank.wedpr.scd.proto.PredicateOrBuilder getAttributePredicateOrBuilder(int index) {
    return attributePredicate_.get(index);
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    for (int i = 0; i < revealedAttributeName_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(
          output, 1, revealedAttributeName_.getRaw(i));
    }
    for (int i = 0; i < attributePredicate_.size(); i++) {
      output.writeMessage(2, attributePredicate_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < revealedAttributeName_.size(); i++) {
        dataSize += computeStringSizeNoTag(revealedAttributeName_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRevealedAttributeNameList().size();
    }
    for (int i = 0; i < attributePredicate_.size(); i++) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(2, attributePredicate_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.webank.wedpr.scd.proto.VerificationRuleSet)) {
      return super.equals(obj);
    }
    com.webank.wedpr.scd.proto.VerificationRuleSet other =
        (com.webank.wedpr.scd.proto.VerificationRuleSet) obj;

    if (!getRevealedAttributeNameList().equals(other.getRevealedAttributeNameList())) return false;
    if (!getAttributePredicateList().equals(other.getAttributePredicateList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getRevealedAttributeNameCount() > 0) {
      hash = (37 * hash) + REVEALED_ATTRIBUTE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getRevealedAttributeNameList().hashCode();
    }
    if (getAttributePredicateCount() > 0) {
      hash = (37 * hash) + ATTRIBUTE_PREDICATE_FIELD_NUMBER;
      hash = (53 * hash) + getAttributePredicateList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.webank.wedpr.scd.proto.VerificationRuleSet prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Verification rule set.
   * </pre>
   *
   * Protobuf type {@code com.webank.wedpr.scd.proto.VerificationRuleSet}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:com.webank.wedpr.scd.proto.VerificationRuleSet)
      com.webank.wedpr.scd.proto.VerificationRuleSetOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.webank.wedpr.scd.proto.Scd
          .internal_static_com_webank_wedpr_scd_proto_VerificationRuleSet_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return com.webank.wedpr.scd.proto.Scd
          .internal_static_com_webank_wedpr_scd_proto_VerificationRuleSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.webank.wedpr.scd.proto.VerificationRuleSet.class,
              com.webank.wedpr.scd.proto.VerificationRuleSet.Builder.class);
    }

    // Construct using com.webank.wedpr.scd.proto.VerificationRuleSet.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        getAttributePredicateFieldBuilder();
      }
    }

    @Override
    public Builder clear() {
      super.clear();
      revealedAttributeName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (attributePredicateBuilder_ == null) {
        attributePredicate_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        attributePredicateBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.webank.wedpr.scd.proto.Scd
          .internal_static_com_webank_wedpr_scd_proto_VerificationRuleSet_descriptor;
    }

    @Override
    public com.webank.wedpr.scd.proto.VerificationRuleSet getDefaultInstanceForType() {
      return com.webank.wedpr.scd.proto.VerificationRuleSet.getDefaultInstance();
    }

    @Override
    public com.webank.wedpr.scd.proto.VerificationRuleSet build() {
      com.webank.wedpr.scd.proto.VerificationRuleSet result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public com.webank.wedpr.scd.proto.VerificationRuleSet buildPartial() {
      com.webank.wedpr.scd.proto.VerificationRuleSet result =
          new com.webank.wedpr.scd.proto.VerificationRuleSet(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        revealedAttributeName_ = revealedAttributeName_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.revealedAttributeName_ = revealedAttributeName_;
      if (attributePredicateBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          attributePredicate_ = java.util.Collections.unmodifiableList(attributePredicate_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.attributePredicate_ = attributePredicate_;
      } else {
        result.attributePredicate_ = attributePredicateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.webank.wedpr.scd.proto.VerificationRuleSet) {
        return mergeFrom((com.webank.wedpr.scd.proto.VerificationRuleSet) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.webank.wedpr.scd.proto.VerificationRuleSet other) {
      if (other == com.webank.wedpr.scd.proto.VerificationRuleSet.getDefaultInstance()) return this;
      if (!other.revealedAttributeName_.isEmpty()) {
        if (revealedAttributeName_.isEmpty()) {
          revealedAttributeName_ = other.revealedAttributeName_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRevealedAttributeNameIsMutable();
          revealedAttributeName_.addAll(other.revealedAttributeName_);
        }
        onChanged();
      }
      if (attributePredicateBuilder_ == null) {
        if (!other.attributePredicate_.isEmpty()) {
          if (attributePredicate_.isEmpty()) {
            attributePredicate_ = other.attributePredicate_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAttributePredicateIsMutable();
            attributePredicate_.addAll(other.attributePredicate_);
          }
          onChanged();
        }
      } else {
        if (!other.attributePredicate_.isEmpty()) {
          if (attributePredicateBuilder_.isEmpty()) {
            attributePredicateBuilder_.dispose();
            attributePredicateBuilder_ = null;
            attributePredicate_ = other.attributePredicate_;
            bitField0_ = (bitField0_ & ~0x00000002);
            attributePredicateBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                    ? getAttributePredicateFieldBuilder()
                    : null;
          } else {
            attributePredicateBuilder_.addAllMessages(other.attributePredicate_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.webank.wedpr.scd.proto.VerificationRuleSet parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.webank.wedpr.scd.proto.VerificationRuleSet) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.LazyStringList revealedAttributeName_ =
        com.google.protobuf.LazyStringArrayList.EMPTY;

    private void ensureRevealedAttributeNameIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        revealedAttributeName_ =
            new com.google.protobuf.LazyStringArrayList(revealedAttributeName_);
        bitField0_ |= 0x00000001;
      }
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public com.google.protobuf.ProtocolStringList getRevealedAttributeNameList() {
      return revealedAttributeName_.getUnmodifiableView();
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public int getRevealedAttributeNameCount() {
      return revealedAttributeName_.size();
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public String getRevealedAttributeName(int index) {
      return revealedAttributeName_.get(index);
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public com.google.protobuf.ByteString getRevealedAttributeNameBytes(int index) {
      return revealedAttributeName_.getByteString(index);
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public Builder setRevealedAttributeName(int index, String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRevealedAttributeNameIsMutable();
      revealedAttributeName_.set(index, value);
      onChanged();
      return this;
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public Builder addRevealedAttributeName(String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureRevealedAttributeNameIsMutable();
      revealedAttributeName_.add(value);
      onChanged();
      return this;
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public Builder addAllRevealedAttributeName(Iterable<String> values) {
      ensureRevealedAttributeNameIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(values, revealedAttributeName_);
      onChanged();
      return this;
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public Builder clearRevealedAttributeName() {
      revealedAttributeName_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /** <code>repeated string revealed_attribute_name = 1;</code> */
    public Builder addRevealedAttributeNameBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      ensureRevealedAttributeNameIsMutable();
      revealedAttributeName_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<com.webank.wedpr.scd.proto.Predicate> attributePredicate_ =
        java.util.Collections.emptyList();

    private void ensureAttributePredicateIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        attributePredicate_ =
            new java.util.ArrayList<com.webank.wedpr.scd.proto.Predicate>(attributePredicate_);
        bitField0_ |= 0x00000002;
      }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.webank.wedpr.scd.proto.Predicate,
            com.webank.wedpr.scd.proto.Predicate.Builder,
            com.webank.wedpr.scd.proto.PredicateOrBuilder>
        attributePredicateBuilder_;

    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public java.util.List<com.webank.wedpr.scd.proto.Predicate> getAttributePredicateList() {
      if (attributePredicateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attributePredicate_);
      } else {
        return attributePredicateBuilder_.getMessageList();
      }
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public int getAttributePredicateCount() {
      if (attributePredicateBuilder_ == null) {
        return attributePredicate_.size();
      } else {
        return attributePredicateBuilder_.getCount();
      }
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public com.webank.wedpr.scd.proto.Predicate getAttributePredicate(int index) {
      if (attributePredicateBuilder_ == null) {
        return attributePredicate_.get(index);
      } else {
        return attributePredicateBuilder_.getMessage(index);
      }
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder setAttributePredicate(int index, com.webank.wedpr.scd.proto.Predicate value) {
      if (attributePredicateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributePredicateIsMutable();
        attributePredicate_.set(index, value);
        onChanged();
      } else {
        attributePredicateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder setAttributePredicate(
        int index, com.webank.wedpr.scd.proto.Predicate.Builder builderForValue) {
      if (attributePredicateBuilder_ == null) {
        ensureAttributePredicateIsMutable();
        attributePredicate_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributePredicateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder addAttributePredicate(com.webank.wedpr.scd.proto.Predicate value) {
      if (attributePredicateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributePredicateIsMutable();
        attributePredicate_.add(value);
        onChanged();
      } else {
        attributePredicateBuilder_.addMessage(value);
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder addAttributePredicate(int index, com.webank.wedpr.scd.proto.Predicate value) {
      if (attributePredicateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributePredicateIsMutable();
        attributePredicate_.add(index, value);
        onChanged();
      } else {
        attributePredicateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder addAttributePredicate(
        com.webank.wedpr.scd.proto.Predicate.Builder builderForValue) {
      if (attributePredicateBuilder_ == null) {
        ensureAttributePredicateIsMutable();
        attributePredicate_.add(builderForValue.build());
        onChanged();
      } else {
        attributePredicateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder addAttributePredicate(
        int index, com.webank.wedpr.scd.proto.Predicate.Builder builderForValue) {
      if (attributePredicateBuilder_ == null) {
        ensureAttributePredicateIsMutable();
        attributePredicate_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributePredicateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder addAllAttributePredicate(
        Iterable<? extends com.webank.wedpr.scd.proto.Predicate> values) {
      if (attributePredicateBuilder_ == null) {
        ensureAttributePredicateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(values, attributePredicate_);
        onChanged();
      } else {
        attributePredicateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder clearAttributePredicate() {
      if (attributePredicateBuilder_ == null) {
        attributePredicate_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        attributePredicateBuilder_.clear();
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public Builder removeAttributePredicate(int index) {
      if (attributePredicateBuilder_ == null) {
        ensureAttributePredicateIsMutable();
        attributePredicate_.remove(index);
        onChanged();
      } else {
        attributePredicateBuilder_.remove(index);
      }
      return this;
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public com.webank.wedpr.scd.proto.Predicate.Builder getAttributePredicateBuilder(int index) {
      return getAttributePredicateFieldBuilder().getBuilder(index);
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public com.webank.wedpr.scd.proto.PredicateOrBuilder getAttributePredicateOrBuilder(int index) {
      if (attributePredicateBuilder_ == null) {
        return attributePredicate_.get(index);
      } else {
        return attributePredicateBuilder_.getMessageOrBuilder(index);
      }
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public java.util.List<? extends com.webank.wedpr.scd.proto.PredicateOrBuilder>
        getAttributePredicateOrBuilderList() {
      if (attributePredicateBuilder_ != null) {
        return attributePredicateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attributePredicate_);
      }
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public com.webank.wedpr.scd.proto.Predicate.Builder addAttributePredicateBuilder() {
      return getAttributePredicateFieldBuilder()
          .addBuilder(com.webank.wedpr.scd.proto.Predicate.getDefaultInstance());
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public com.webank.wedpr.scd.proto.Predicate.Builder addAttributePredicateBuilder(int index) {
      return getAttributePredicateFieldBuilder()
          .addBuilder(index, com.webank.wedpr.scd.proto.Predicate.getDefaultInstance());
    }
    /** <code>repeated .com.webank.wedpr.scd.proto.Predicate attribute_predicate = 2;</code> */
    public java.util.List<com.webank.wedpr.scd.proto.Predicate.Builder>
        getAttributePredicateBuilderList() {
      return getAttributePredicateFieldBuilder().getBuilderList();
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            com.webank.wedpr.scd.proto.Predicate,
            com.webank.wedpr.scd.proto.Predicate.Builder,
            com.webank.wedpr.scd.proto.PredicateOrBuilder>
        getAttributePredicateFieldBuilder() {
      if (attributePredicateBuilder_ == null) {
        attributePredicateBuilder_ =
            new com.google.protobuf.RepeatedFieldBuilderV3<
                com.webank.wedpr.scd.proto.Predicate,
                com.webank.wedpr.scd.proto.Predicate.Builder,
                com.webank.wedpr.scd.proto.PredicateOrBuilder>(
                attributePredicate_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        attributePredicate_ = null;
      }
      return attributePredicateBuilder_;
    }

    @Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:com.webank.wedpr.scd.proto.VerificationRuleSet)
  }

  // @@protoc_insertion_point(class_scope:com.webank.wedpr.scd.proto.VerificationRuleSet)
  private static final com.webank.wedpr.scd.proto.VerificationRuleSet DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.webank.wedpr.scd.proto.VerificationRuleSet();
  }

  public static com.webank.wedpr.scd.proto.VerificationRuleSet getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerificationRuleSet> PARSER =
      new com.google.protobuf.AbstractParser<VerificationRuleSet>() {
        @Override
        public VerificationRuleSet parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new VerificationRuleSet(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<VerificationRuleSet> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<VerificationRuleSet> getParserForType() {
    return PARSER;
  }

  @Override
  public com.webank.wedpr.scd.proto.VerificationRuleSet getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
