// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scd.proto

package com.webank.wedpr.scd.proto;

public interface BlindedCertificateSecretOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:com.webank.wedpr.scd.proto.BlindedCertificateSecret)
        com.google.protobuf.MessageOrBuilder {

    /** <code>string blinded_certificate_secrets = 1;</code> */
    String getBlindedCertificateSecrets();
    /** <code>string blinded_certificate_secrets = 1;</code> */
    com.google.protobuf.ByteString getBlindedCertificateSecretsBytes();

    /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
    String getBlindedCertificateSecretsCorrectnessProof();
    /** <code>string blinded_certificate_secrets_correctness_proof = 2;</code> */
    com.google.protobuf.ByteString getBlindedCertificateSecretsCorrectnessProofBytes();
}
