name: Java-SDK GitHub Actions
on:
  push:
  pull_request:
  release:
    types: [published, created, edited]
env:
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install openjdk
      - name: install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt install -y git curl default-jdk build-essential
      - name: download dynamic libs
        run: |
          curl -LO https://github.com/WeBankBlockchain/WeDPR-Lab-Core/releases/download/v1.1.0/java_sdk_dynamic_lib_linux.tar.gz
          tar zxvf java_sdk_dynamic_lib_linux.tar.gz
          cp ./java_sdk_dynamic_lib_linux/* ./demo/src/main/resources/WeDPR_dynamic_lib/
      - name: compile and run ut
        run: bash ./gradlew clean build
      # - name: run demo
      #   run: cd demo/dist/ && java -cp "apps/*:conf/:libs/*" com.webank.wedpr.demo.DemoMain
